- .bin/format.sh
- app/containers/Applications/ApplicationWizardStep.js
- app/containers/Organisations/Facility.js
- app/containers/Organisations/OrganisationFacilities.js
- app/containers/Organisations/Organisations.js
- app/containers/Organisations/UserOrganisation.js
- app/containers/pageContainers/UserOrganisationFacilities.js
- app/package.json
- app/pages/user-organisation-facilities.js
- app/server/schema.graphql
- app/server/schema.json
- schema/deploy/table_user_organisation.sql
Adds a facilities page that contains cards for all facilities of an organsation & links to their applications in progress or has a button to start a new application.
> Facilities by organisation

- app/package.json
- app/yarn.lock
```
$ yarn upgrade
```
This commit is indended to close a bunch of dependabot PRs in one go...
> bump all js versions in lock file

- app/containers/Organisations/Facility.js
- app/containers/Organisations/Organisations.js
- app/mutations/application/createApplicationMutation.js
- app/server/schema.graphql
- app/server/schema.json
- app/tests/containers/Organisation/Facility.test.js
- app/tests/containers/Organisation/Organisation.test.js
- app/tests/containers/Organisation/OrganisationFacilities.test.js
- app/tests/containers/Organisation/Organisations.test.js
- app/tests/containers/Organisation/UserOrganisation.test.js
- app/tests/containers/Organisation/__snapshots__/Facility.test.js.snap
- app/tests/containers/Organisation/__snapshots__/Organisation.test.js.snap
- app/tests/containers/Organisation/__snapshots__/OrganisationFacilities.test.js.snap
- app/tests/containers/Organisation/__snapshots__/Organisations.test.js.snap
- app/tests/containers/Organisation/__snapshots__/UserOrganisation.test.js.snap
- app/tests/mutations/application/createApplicationMutation.test.js
- app/tests/pages/__snapshots__/user-dashboard.test.js.snap
- app/tests/pages/__snapshots__/user-organisation-facilities.test.js.snap
- app/tests/pages/user-organisation-facilities.test.js
- schema/deploy/function_create_application_mutation_chain.sql
- schema/deploy/function_insert_dummy_application_data.sql
- schema/revert/function_create_application_mutation_chain.sql
- schema/sqitch.plan
- schema/verify/function_create_application_mutation_chain.sql
Added a stored procedure to cover createApplication -> createApplicationStatus mutation chain, renders a status in facility view && conditionally renders the apply/resume application button
> Re-implement application status

- app/containers/Applications/ApplicationWizard.js
- app/containers/Applications/ApplicationWizardConfirmation.js
- app/containers/Applications/ApplicationWizardConfirmationCardItem.js
- app/containers/Applications/ApplicationWizardStep.js
- app/mutations/application/updateApplicationStatusMutation.js
- app/tests/containers/Applications/__snapshots__/applicationWizardConfirmation.test.js.snap
- app/tests/containers/Applications/__snapshots__/applicationWizardConfirmationCardItem.test.js.snap
- app/tests/containers/Applications/applicationWizardConfirmation.test.js
- app/tests/containers/Applications/applicationWizardConfirmationCardItem.test.js
- app/tests/containers/Organisation/Organisation.test.js
- app/tests/containers/Organisation/UserOrganisation.test.js
- schema/deploy/function_insert_dummy_application_data.sql
Adds a page at the end of the ciip application that shows all formResult data on one page and renders a 'Submit' button that when clicked changes the application status from 'draft' to 'pending'
> Summary / confirmation page

- app/components/Layout/Header.js
- app/pages/_document.js
- app/tests/components/Layout/__snapshots__/Header.test.js.snap
- app/tests/layout/__snapshots__/Default-layout.test.js.snap
This prevents the pages from doing an initial unstyled render.
> feature: added custom stylesheets to _document to load them on server side

- app/components/Forms/ApplicationFormNavbar.tsx
- app/containers/Applications/ApplicationWizardStep.tsx
- app/containers/Forms/Form.tsx
- app/lib/relay-environment/client.ts
- app/lib/relay-environment/server.ts
- app/pages/_app.tsx
- app/tests/pages/application-details.test.tsx
This PR has removed SSR from relay, which fixes the react navigation tabs.
Relay SSR appears to be somewhat broken at the moment with active Issues and PRs:
https://github.com/facebook/relay/issues/1881
https://github.com/facebook/relay/pull/2883
> Remove relay SSR

- app/containers/Forms/Form.tsx
- schema/data/portal/form_json/electricity_and_heat.json
Changes json file to work with json-schema
Adds props & custom submit button to JsonSchemaForm
> Migrate heat and gas form to json-schema form

- app/containers/Applications/ApplicationStatusContainer.tsx
- app/containers/Products/ProductCreatorContainer.tsx
- app/containers/Products/ProductListContainer.tsx
- app/mutations/application/updateApplicationStatusByRowIdMutation.ts
- app/mutations/application/updateApplicationStatusMutation.ts
- app/mutations/benchmark/createBenchmarkMutation.ts
- app/mutations/benchmark/editBenchmarkMutation.ts
- app/mutations/industry/editUserMutation.ts
- app/mutations/product/createProductMutation.ts
- app/mutations/product/saveProductMutation.ts
- app/mutations/user_organisation/UpdateUserOrganisation.ts
- app/pages/application-details.tsx
> Move mutations to its own files

- app/mutations/BaseMutation.ts
- app/mutations/form/updateFormResultMutation.ts
- app/mutations/user/createUserMutation.ts
- app/mutations/user/updateUserMutation.ts
- app/mutations/user_organisation/UserOrganisation.ts
A couple user variables were missed when we renamed the user table. This fixes them.
> hotfix - user -> ciipUser fix

- app/pages/user-dashboard.tsx
userOrganisation -> ciipUserOrganisation
> rename userOrganisation to ciipUserOrganision in mutation

- app/server/schema.graphql
- app/server/schema.json
- schema/deploy/function_create_application_mutation_chain.sql
- schema/deploy/view_ciip_application.sql
- schema/deploy/view_ciip_certifier.sql
- schema/deploy/view_ciip_electricity_and_heat.sql
- schema/deploy/view_ciip_fuel.sql
- schema/deploy/view_ciip_production.sql
fixed electricity & heat, production, fuel & applicaiton views after change to jsonSchema
> Fix ciip views

- app/components/Layout/Footer.tsx
- app/pages/resources/accessibility.tsx
- app/pages/resources/contact.tsx
- app/pages/resources/copyright.tsx
- app/pages/resources/disclaimer.tsx
- app/pages/resources/privacy.tsx
- app/tests/components/Layout/__snapshots__/Footer.test.tsx.snap
- app/tests/storyShots/__snapshots__/Admin.stories.storyshot
Link styles were applying, as per this [issue](https://github.com/zeit/next.js/issues/610), so had to fix by adding :global(a).
> Add footer links

- app/package.json
- app/server/index.js
- app/yarn.lock
[GraphQL Voyager] represents any GraphQL API as an interactive graph. This PR adds a `/voyager` endpoint to enable graph-based exploration of the CIIP Portal schema.
[GraphQL Voyager]: https://github.com/APIs-guru/graphql-voyager
> feature(app/server): add graphql-voyager endpoint

- .watch-server.json
- app/server/index.js
- docs/developer-guide.md
- schema/data/portal/user.sql
This is now the default behavior when running make watch
> feature: add NO_AUTH option to server to disable keycloak auth.

- app/components/Layout/Header.tsx
- app/layouts/default-layout.tsx
- app/tests/layout/__snapshots__/default-layout.test.tsx.snap
- app/tests/storyShots/__snapshots__/Admin.stories.storyshot
- schema/deploy/function_session.sql
there's currently no way to abort registration if we signed in with the wrong account; fixed here
> fix(authentication): ensure malformed sessions are recoverable by logout

- .circleci/config.yml
- app/features/admin/authentication.feature
- app/features/admin/authorization.feature
- app/features/admin/benchmarks.feature
- app/features/admin/products.feature
- app/features/admin/registration.feature
- app/features/analyst/authentication.feature
- app/features/analyst/ciip-filing.feature
- app/features/analyst/ciip-filings.feature
- app/features/analyst/registration.feature
- app/features/ciip-mvp.md
- app/features/executive/availability.feature
- app/features/executive/business-continuity.feature
- app/features/industry/authentication.feature
- app/features/industry/ciip-filing.feature
- app/features/industry/dry.feature
- app/features/industry/email.feature
- app/features/industry/registration.feature
- app/package.json
- app/yarn.lock
The list of MVP-targeted features can be reviewed with a `yarn cucumber:pretty` and are all tagged with an `@mvp` if scheduled for inclusion.
This preliminary list is based on the 70/30 MVP diagram reviewed yesterday:
> mvp features in cucumber form

- README.md
For in-progress self-certification (as discussed)
> Feature(docs): add CII Best Practices badge

- app/containers/Applications/ApplicationCommentsByForm.tsx
- app/containers/Applications/ApplicationCommentsContainer.tsx
- app/containers/Applications/ApplicationReviewContainer.tsx
- app/mutations/application/createApplicationReviewMutation.ts
- app/tests/unit/containers/Applications/__snapshots__/ApplicationCommentsContainer.test.tsx.snap
- app/tests/unit/containers/Applications/__snapshots__/ApplicationReviewContainer.test.tsx.snap
- app/tests/unit/pages/__snapshots__/index.test.tsx.snap
Custom mutation chains using computed columns need to be told how to traverse the graphql graph explicitly so that relay can update the store
> Fix mutation chain response so relay can update the frontend in the Application review flow

- app/containers/Applications/ApplicationCommentsByForm.tsx
- app/containers/Products/FutureBenchmarks.tsx
- app/containers/Products/ProductRowItemContainer.tsx
- app/package.json
- app/pages/certification-redirect.tsx
- app/pages/index.tsx
- app/pages/user-dashboard.tsx
- app/server/schema.graphql
- app/server/schema.json
- app/yarn.lock
- schema/deploy/function_search_all_facilities.sql
- schema/deploy/function_search_products.sql
- schema/deploy/table_ciip_user_organisation.sql
- Change use of 'moment' to 'moment-timezone'
-- all timezones set to Los Angeles (BC) time
- Filter searchAllFacilities results by user_id via session uuid
- Remove instances where user_id was being set on front-end, replaced with psql trigger
> Minor cleanup tasks

- .circleci/config.yml
leaving postgres running causes https://app.circleci.com/jobs/github/bcgov/cas-ciip-portal/11275
> postgres should be stopped after pgtap installation

- schema/deploy/search_functions/search_ciip_user_organisation.sql
- schema/test/unit/search_ciip_user_organisation_test.sql
- The search function was returning a user_organisation type without an id, which is required by the type.
> Fix search function to include id

- app/components/ApplyButton.tsx
- app/components/Checkbox.tsx
- app/components/LegalDisclaimerChecklist.tsx
- app/containers/Applications/LegalDisclaimerChecklistContainer.tsx
- app/mutations/application/updateApplicationRevisionMutation.ts
- app/pages/certifier/certify.tsx
- app/pages/ciip-application-legal-disclaimer.tsx
- app/pages/reporter/ciip-application-legal-disclaimer.tsx
- app/server/schema.graphql
- app/server/schema.json
- schema/deploy/tables/application_revision.sql
added legal disclaimer component to be used in reporter's legal disclaimer page and certifier's certify page
> legal disclaimer

- app/containers/Applications/ApplicationDetailsCardItem.tsx
- app/containers/Applications/ApplicationReviewContainer.tsx
- app/server/schema.graphql
- app/server/schema.json
- schema/deploy/computed_columns/form_result_form_result_statuses.sql
- schema/deploy/mutations/create_application_revision_mutation_chain.sql
- schema/deploy/mutations/create_review_comment_mutation_chain.sql
- schema/deploy/tables/form_result_status.sql
- schema/test/unit/mutations/create_review_comment_mutation_chain_test.sql
- schema/test/unit/trigger_functions/checksum_form_results_test.sql
- schema/verify/mutations/create_review_comment_mutation_chain.sql
It should not have a version number
> Fix: remove version_number from form_result_status table

- schema/deploy/tables/form_json.sql
- schema/deploy/tables/form_result.sql
- schema/deploy/tables/form_result_status.sql
- schema/revert/tables/form_result.sql
- schema/revert/tables/form_result_status.sql
- schema/test/unit/tables/form_json_test.sql
- schema/test/unit/tables/form_result_status_test.sql
- schema/test/unit/tables/form_result_test.sql
- schema/verify/tables/form_json.sql
- schema/verify/tables/form_result.sql
- schema/verify/tables/form_result_status.sql
- form_json table
- form_result table
- form_result_status table
> Row level security: form* tables

- app/components/Layout/Header.tsx
- app/containers/Applications/ApplicationCommentsByForm.tsx
- app/cypress/integration/admin-access-all-pages.spec.js
- app/layouts/default-layout.tsx
- app/pages/analyst/applications.tsx
- app/tests/unit/components/Layout/__snapshots__/Header.test.tsx.snap
- app/tests/unit/containers/Applications/__snapshots__/ApplicationDetailsPdf.test.tsx.snap
- app/tests/unit/layout/__snapshots__/default-layout.test.tsx.snap
- schema/data/prod/form_json/fuel.json
- Fix Fuel units always fail required in Fuel form
- Remove 'Industry' button from header if not logged in as Industry user
- Use optional chaining for user firstName lastName in review comments (industry user cannot view the row in ciip_user table)
- Fix broken Admin dashboard link to Applications list
> Minor bug fixes before deploy to test

- app/cypress/support/commands.js
Hopefully, this fixes one of our flaky failures
> test (e2e): retry logging in if the keycloak portal is unavailable

- app/containers/Forms/FuelFields.tsx
- app/server/index.js
typo: errorSchema.units -> errorSchema.fuelUnits
> Fix: fuel form errorSchema.fuelUnits

- app/cypress/plugins/index.js
- app/package.json
- app/yarn.lock
This did not fix the flaky health check
> Revert fix cypress percy health check

- app/containers/Applications/ApplicationDetailsContainer.tsx
- app/containers/Applications/ApplicationDetailsPdf.tsx
- app/tests/unit/containers/Applications/ApplicationDetailsPdf.test.tsx
- iterates over orderedFormResults which takes a version number as an input instead of formResultsByApplicationId which returned all form results from all versions for an application
> Fix: Pdf duplicate results

- Makefile
+ moved retrieving the last deploy sha1 into the install target
> fix: schema-deploy job name was not updated aver prefix rename

- app/server/index.js
- add AS_USER, AS_ANALYST, AS_ADMIN flags to server to enable quick login as those roles
> Login flags

- app/components/Layout/Subheader.tsx
- app/containers/Applications/ApplicationCommentsContainer.tsx
- app/containers/Facilities/FacilitiesListContainer.tsx
- app/pages/analyst/application-review.tsx
- app/tests/integration/__snapshots__/Storyshots.test.ts.snap
- app/tests/unit/components/Layout/__snapshots__/Subheader.test.tsx.snap
- app/tests/unit/containers/Applications/ApplicationCommentsContainer.test.tsx
- app/tests/unit/containers/Applications/__snapshots__/ApplicationCommentsContainer.test.tsx.snap
- app/tests/unit/pages/__snapshots__/application-review.test.tsx.snap
- schema/deploy/tables/ciip_user.sql
- schema/test/unit/tables/ciip_user_organisation_test.sql
- schema/test/unit/tables/ciip_user_test.sql
- schema/verify/tables/ciip_user.sql
- Add grants/policies allowing analysts to update/insert on ciip_user table (for registration)
- Allow admins to view applications (had missing allowed_groups values)
- Do not show comments to reporter until the application status has been changed to 'requested changes'
- Fix 'My Applications' link in subheader
> Bug fixes from 'test'

- .pre-commit-config.yaml
- app/keycloak-realm-export.json
- docs/docs.md
+ added another exclude in pre-commit detect secrets (this is a temporary solution)
> chore: add keycloak-realm-export.json file

- schema/deploy/swrs_functions/get_swrs_facility_data.sql
limit results (view duplicates some rows)
> Add limit to get_swrs_facility_data()

- app/package.json
Advisory:
https://www.npmjs.com/advisories/1179
> Fix: minimist package vulnerability

- .circleci/config.yml
- app/cypress/integration/admin-access-all-pages.spec.js
- app/cypress/integration/analyst-access-all-pages.spec.js
- app/cypress/integration/analyst-diffing.spec.js
- app/cypress/integration/email.spec.js
- app/server/index.js
- app/server/tasks/sendMail.js
- docs/docs.md
- schema/data/fixtures/add-user.sql
- schema/data/fixtures/analyst-all-access-setup.sql
- schema/data/fixtures/analyst-all-access-teardown.sql
- schema/data/fixtures/analyst-diffing-setup.sql
- schema/data/fixtures/analyst-diffing-teardown.sql
- schema/data/fixtures/application-production-setup.sql
- schema/data/fixtures/change-form-result.sql
- schema/data/fixtures/email-setup.sql
- schema/data/fixtures/email-teardown.sql
- schema/data/fixtures/form-errors-prevent-submit-setup.sql
- schema/data/fixtures/form-validation-setup.sql
- schema/data/fixtures/production-draft-form-result-setup.sql
- schema/data/fixtures/products-benchmarks-setup.sql
- schema/data/fixtures/remove-user.sql
- schema/data/fixtures/reporter-all-access-setup.sql
- Add documentation for starting a mailhog server
- Add NO_MAIL flag to yarn dev
- Add cypress test that tests automatic email send points
- Add Circle job for starting MailHog server
- Begin idea on re-writing fixtures that start with a clean database (truncate application table for each)
> SMTP testing: MailHog

- app/server/index.js
- schema/deploy/tables/ciip_user.sql
- schema/test/unit/tables/ciip_user_test.sql
- schema/verify/tables/ciip_user.sql
- adds `select` grants & privileges on ggircs_portal.ciip_user to role ciip_user
- adds pgTap tests
> Pending Analyst RLS fix

- app/containers/Products/ProductCreatorContainer.tsx
- app/containers/Products/ProductRowItemContainer.tsx
- app/containers/Products/product-schema.json
- app/cypress/integration/product-benchmark.spec.js
- app/mutations/product/saveProductMutation.ts
- app/pages/admin/products-benchmarks.tsx
- app/server/schema.graphql
- app/server/schema.json
- schema/deploy/mutations/save_product_mutation_chain.sql
- schema/deploy/search_functions/search_products.sql
- schema/deploy/tables/product.sql
- schema/verify/mutations/save_product_mutation_chain.sql
- Adds radio buttons to subtract generated heat/electricity from emission intensity
- Closes modal on creation of a product & shows a success toast message (bug fix ggircs-1315 in youtrack)
https://youtrack.button.is/issue/GGIRCS-1315
> Admin can subtract generated heat/electricity

- app/containers/Forms/Form.tsx
- app/tests/integration/Forms/__snapshots__/Form.test.tsx.snap
- app/tests/unit/containers/Forms/__snapshots__/Form.test.tsx.snap
Speculatively fixes note [GGIRCS-1402](https://youtrack.button.is/issue/GGIRCS-1402) (all required fields needing to be filled before input formats are validated).
> 1-step Form Validation

- docs/developer-guide.md
Just adds some extra info about flags & deploying data.
> Documentation update

- app/containers/Facilities/FacilitiesListContainer.tsx
- app/pages/reporter/facilities-list.tsx
- app/server/schema.graphql
- app/server/schema.json
- schema/deploy/search_functions/search_all_facilities.sql
- schema/test/unit/search_functions/function_search_all_facilities_test.sql
- schema/verify/search_functions/search_all_facilities.sql
Fixes https://youtrack.button.is/issue/GGIRCS-1356 "Facilities list does not filter by organisation"
> Fix: Filter facilities page by organisation

- app/containers/Facilities/FacilitiesListContainer.tsx
Fixes https://youtrack.button.is/issue/GGIRCS-1380 "facilities pagination bar can go past last page"
> Fix: Facility pagination bar cannot go past last page

- openshift/deploy/deploymentconfig/app.yml
This uses the feature added in #587
> feat: set HOST env variable when deploying the app

- schema/deploy/search_functions/search_all_facilities.sql
Fixes https://youtrack.button.is/issue/GGIRCS-1430 by modifying location of a join in the search function
> Fix: search facilities - revision status bug

- app/package.json
- app/yarn.lock
https://www.npmjs.com/advisories/1500
> chore(deps): add security resolution for yargs-parser

- app/containers/Applications/ApplicationDetailsPdf.tsx
- app/containers/Facilities/FacilitiesListContainer.tsx
- app/containers/Facilities/FacilitiesRowItemContainer.tsx
- app/server/schema.graphql
- app/server/schema.json
- app/tests/unit/containers/Applications/__snapshots__/ApplicationDetailsPdf.test.tsx.snap
- app/tests/unit/containers/Facility/__snapshots__/FacilitiesListContainer.test.tsx.snap
- schema/deploy/search_functions/search_all_facilities.sql
- schema/deploy/tables/facility.sql
- schema/deploy/types/facility_search_result.sql
> feat: facility table displays type, ghg id and last swrs report year

- app/components/Dashboard/applicationManagement.tsx
- app/components/Dashboard/userManagement.tsx
- app/cypress/integration/admin-access-all-pages.spec.js
- app/cypress/integration/analyst-access-all-pages.spec.js
- app/pages/analyst/organisation-requests.tsx
- app/stories/Pages.stories.tsx
- app/tests/integration/__snapshots__/Storyshots.test.ts.snap
- schema/deploy/tables/ciip_user_organisation.sql
- schema/test/unit/tables/ciip_user_organisation_test.sql
- schema/verify/tables/ciip_user_organisation.sql
- Change row level security for analyst access to user_organisation table
- Change group permissions & relocates user-organisation page from admin directory to analyst directory
- Update jest/cypress/pgTap tests
> feat: Allow analysts to whitelist user-org requests

- app/containers/Forms/Form.tsx
- app/tests/unit/containers/Forms/Form.test.tsx
- app/tests/unit/containers/Forms/__snapshots__/Form.test.tsx.snap
- Adds an alert  reminder to check the guidance documents if any product on the product page requires emission allocation
- Adds jest unit tests
> feat(product): Show a guidance reminder alert for emission allocation

- app/containers/Applications/ApplicationWizardConfirmation.tsx
- app/cypress/integration/email.spec.js
- app/tests/unit/containers/Applications/__snapshots__/ApplicationWizardConfirmation.test.tsx.snap
- schema/deploy/tables/certification_url.sql
- Make the default behaviour sending the email & require the user to 'opt-out'
> chore(certifier): Set 'SendEmail' default to 'true'

- app/components/SortableTableHeader.tsx
- app/containers/Admin/OrganisationRequestsTable.tsx
- app/containers/Applications/ApplicationListContainer.tsx
- app/containers/Applications/ApplicationWizardConfirmation.tsx
- app/containers/Facilities/FacilitiesListContainer.tsx
- app/containers/Products/ProductCreatorContainer.tsx
- app/cypress/integration/email.spec.js
- app/tests/unit/containers/Applications/__snapshots__/ApplicationListContainer.test.tsx.snap
- app/tests/unit/containers/Applications/__snapshots__/ApplicationWizardConfirmation.test.tsx.snap
- app/tests/unit/containers/Facility/__snapshots__/FacilitiesListContainer.test.tsx.snap
- app/tests/unit/containers/Organisation/__snapshots__/OrganisationRequestsTable.test.tsx.snap
- Fixes un-uncheckable box in send email to certifier optional checkbox
- Removes redundant jsonschemaform title from product creator modal
- Fixes cut-off table headers for button columns
- Fixes mixed up table header in organisation-requests table (status <--> organisation was mixed up)
> Fix: minor bug cleanup

- app/containers/Organisations/Organisations.tsx
- app/cypress/integration/email.spec.js
- app/cypress/integration/reporter-certifier-access.spec.js
- app/pages/reporter/user-dashboard.tsx
- app/server/emailTemplates/certificationRequest.js
- app/server/tasks/sendMail.js
- app/tests/integration/__snapshots__/Storyshots.test.ts.snap
- app/tests/unit/containers/Organisation/Organisations.test.tsx
- app/tests/unit/containers/Organisation/__snapshots__/Organisations.test.tsx.snap
- app/tests/unit/pages/__snapshots__/user-dashboard.test.tsx.snap
- app/tests/unit/pages/user-dashboard.test.tsx
- Adds link to certification requests list page (`/certifier/certify`):
* on the reporter dash
* in the request email to certifier
- Adds navigation of email and dash links to end-to-end tests
[GGIRCS-1394](https://youtrack.button.is/issue/GGIRCS-1394)
> Link to batch certify page from dash and email

- Makefile
- README.md
Updated the README.md for the CIIP Portal to add more detail and structure.
> Ggircs 1085

- schema/data/prod/fuel.sql
- schema/deploy/computed_columns/application_revision_ciip_incentive.sql
- schema/deploy/database_functions/set_general_permissions.sql
- schema/deploy/policies/review_comment_policies.sql
- schema/deploy/swrs_functions/get_swrs_operator_contact_data.sql
- schema/deploy/tables/certification_url.sql
- schema/deploy/tables/ciip_application_wizard.sql
- schema/deploy/tables/form_json.sql
- schema/deploy/tables/organisation.sql
- schema/deploy/trigger_functions/run_graphile_worker_job.sql
- schema/deploy/types/jwt_token.sql
- schema/verify/database_functions/set_general_permissions.sql
- The TODOs in the ciip database have been removed & turned into tech debt cards in youtrack
> chore: Remove ciip db todos

- app/containers/Organisations/Organisations.tsx
- app/pages/reporter/user-dashboard.tsx
- app/tests/integration/__snapshots__/Storyshots.test.ts.snap
- app/tests/unit/containers/Organisation/__snapshots__/Organisations.test.tsx.snap
- app/tests/unit/pages/__snapshots__/user-dashboard.test.tsx.snap
Finalizes copy and links on the reporter dashboard, per [GGIRCS-1512](https://youtrack.button.is/issue/GGIRCS-1512).
> Finalize copy on reporter dashboard

- app/containers/Organisations/Organisations.tsx
- app/tests/integration/__snapshots__/Storyshots.test.ts.snap
- app/tests/unit/containers/Organisation/__snapshots__/Organisations.test.tsx.snap
followup fix re: [GGIRCS-1512](https://youtrack.button.is/issue/GGIRCS-1512)
> fix: Add omitted word from reporter dash copy

- app/containers/Applications/ApplicationWizardConfirmation.tsx
- app/tests/unit/containers/Applications/__snapshots__/ApplicationWizardConfirmation.test.tsx.snap
- Copy updates in application summary tab per [GGIRCS-1515](https://youtrack.button.is/issue/GGIRCS-1515)
> Finalize copy on application summary page

- app/package.json
- app/yarn.lock
- Removes old yarn resolutions that are no longer necessary after updates to the affected packages.
> Fix: Remove unnecessary resolutions

- app/cypress/integration/application-form-validation.spec.js
- app/tests/integration/Forms/__snapshots__/Form.test.tsx.snap
- app/tests/unit/containers/Applications/__snapshots__/ApplicationDetailsPdf.test.tsx.snap
- schema/data/fixtures/certifier-access-setup.sql
- schema/data/fixtures/change-form-result.sql
- schema/data/fixtures/email-setup.sql
- schema/data/fixtures/reporter-all-access-setup.sql
- schema/data/prod/form_json/administration.json
Removes some unnecessary form fields, per [GGIRCS-1514](https://youtrack.button.is/issue/GGIRCS-1514):
- Operator DUNS
- Facility NAICS code, mailing address, and "is facility location different from mailing address"
> Finalize form administration section

- app/components/SearchTableLayout.tsx
- app/components/SignatureDisclaimerCard.tsx
- app/containers/Certifier/CertificationRequestsContainer.tsx
- app/containers/Forms/CertificationSignature.tsx
- app/cypress/integration/reporter-certifier-access.spec.js
- app/pages/certifier/certify.tsx
- app/pages/certifier/requests.tsx
- app/server/index.js
- app/tests/unit/components/SignatureDisclaimerCard.test.tsx
- app/tests/unit/components/__snapshots__/SignatureDisclaimerCard.test.tsx.snap
- app/tests/unit/containers/Forms/CertificationSignature.test.tsx
- app/tests/unit/containers/Forms/__snapshots__/CertificationSignature.test.tsx.snap
- app/tests/unit/pages/__snapshots__/certifier-requests.test.tsx.snap
- app/tests/unit/pages/__snapshots__/certify.test.tsx.snap
- schema/data/fixtures/certifier-access-setup.sql
- schema/data/fixtures/certifier-access-teardown.sql
- Select certification requests individually and Select All on `/certifier/requests` page
- Application and legal disclaimer text appears along with signature component
- Certifier can sign off on the selected applications at the same time (only the ones that are currently in view, based on the search/filter query).
Included is a refactor of the CertificationSignature component, which can now provide signing for multiple certification requests at a time.
[GGIRCS-1520](https://youtrack.button.is/issue/GGIRCS-1520)
> Batch certify

- app/containers/Forms/Form.tsx
- app/containers/Forms/ProductField.tsx
- schema/data/prod/energy_product.sql
- creates a validation error for each energy product if it is required+missing
> feat: Front-end energy product validation

- schema/data/prod/emission_gas.sql
- schema/data/prod/gas.sql
- adds 3 gases & their gwp values to the gases table & links them to industrial process emissions
> feat: add hydrofluorocarbons to industrial process emissions

- helm/cas-ciip-portal/templates/deploy.yaml
- helm/cas-ciip-portal/values-wksv3k-dev.yaml
- helm/cas-ciip-portal/values-wksv3k-prod.yaml
- helm/cas-ciip-portal/values-wksv3k-test.yaml
- helm/cas-ciip-portal/values.yaml
resolves deployment error introduced in #764 for GGIRCS-1610
> fix: routes must conform to DNS 952 form

- schema/data/deploy-data.sh
Fixes failed deployment of #733 in dev environment
> fix: deploy-data script always deploys the latest sqitch changes

- app/server/index.js
- helm/cas-ciip-portal/templates/cron-acme-issue.yaml
- helm/cas-ciip-portal/templates/deploy.yaml
- helm/cas-ciip-portal/templates/pvc-acme-challenge.yaml
- helm/cas-ciip-portal/templates/pvc-acme-home.yaml
- helm/cas-ciip-portal/values.yaml
untested; best guess at how to do this given it seems we can't use any of the supported k8s Let's Encrypt provisioners
> feat: use acme.sh to provision ssl certificates

- app/components/Layout/Header.tsx
- app/tests/integration/__snapshots__/Storyshots.test.ts.snap
- app/tests/unit/components/Layout/__snapshots__/Header.test.tsx.snap
Removes unnecessary display property on site header causing it to appear collapsed on Safari.
> Fix block layout of site header on Safari

- helm/cas-ciip-portal/templates/deploy.yaml
> fix: liveness needs to be checked using https

- helm/cas-ciip-portal/values-wksv3k-prod.yaml
- helm/cas-ciip-portal/values-wksv3k-test.yaml
cert generation went out in #787 and now we have a cert for every environment provisioned :)
> feat: use https in all environments

- app/server/index.js
According to numerous Rocket Chat threads and https://github.com/bcgov/ocp-sso/issues/4 the logout function only clears the Keycloak session and never clears the SiteMinder SSO session.
This fix attempts to purge the SiteMinder cookie on logout when we're deployed on a subdomain of .gov.bc.ca
> feat: nuke the siteminder session cookie on logout

- app/containers/Facilities/AddFacility.tsx
- app/pages/analyst/add-facility.tsx
- "operator" --> "facility"
- Grammar/spelling/pluralization/capitalization
> fix: Correct some typos on Add facility page

- app/containers/Forms/CertificationSignature.tsx
- app/tests/unit/containers/Forms/__snapshots__/CertificationSignature.test.tsx.snap
- adds a toast & redirect on signature
> Feat: signature feedback

- app/pages/index.tsx
- app/tests/unit/pages/__snapshots__/index.test.tsx.snap
Updates the link to PDF factsheet for 2020, per [GGIRCS-1724](https://youtrack.button.is/issue/GGIRCS-1724)
> Updated factsheet for 2020 (landing page)

- app/components/Layout/Header.tsx
- app/layouts/default-layout.tsx
- app/tests/integration/__snapshots__/Storyshots.test.ts.snap
- app/tests/unit/components/Layout/__snapshots__/Header.test.tsx.snap
- app/tests/unit/layout/__snapshots__/default-layout.test.tsx.snap
- Updates 'Industry'/'Admin' label for dashboard button in header to 'Dashboard' per [GGIRCS-1665](https://youtrack.button.is/issue/GGIRCS-1665) (encompasses all roles)
- Improves accessibility of 'Dashboard' and 'Profile' links in header by using anchor tag
* use of form + submit buttons for the sole purpose of navigation not in line with best practise. 
- ie: those that use get method with no form data
* anchor tags gives the user access to the right-click context menu to open in new tab/window, copy link address/text, shows a preview of the target URL on hover, etc.
> 'Dashboard' button in header

- schema/deploy/tables/application_001.sql
- schema/revert/tables/application_001.sql
- schema/sqitch.plan
- schema/verify/tables/application_001.sql
fixes multiple 'apply' button clicks bug:
https://youtrack.button.is/issue/GGIRCS-1601
> fix: add uindex to application table

- app/pages/analyst/add-organisation.tsx
Minor capitalization fix. Goes along with #823 - I just didn't notice at the time that this page was added at the same time as the Add Facilities page.
> Capitalize SWRS acronym on Add Organisation page (analyst)

- app/components/Layout/Analytics.jsx
- app/next.config.js
- app/pages/_document.tsx
- helm/cas-ciip-portal/templates/deploy.yaml
- helm/cas-ciip-portal/values-wksv3k-test.yaml
- helm/cas-ciip-portal/values.yaml
Installs test tracker snippet for GDX snowplow analytics, currently intended for test environment only.
> Install test analytics module

- app/components/Layout/SiteNoticeBanner.tsx
- app/layouts/default-layout.tsx
- app/next.config.js
- helm/cas-ciip-portal/templates/deploy.yaml
- helm/cas-ciip-portal/values-wksv3k-dev.yaml
- helm/cas-ciip-portal/values-wksv3k-test.yaml
- helm/cas-ciip-portal/values.yaml
Mobile menu closed   | Mobile menu opened
:---------------------|----------------------:
> Sitewide notice banner

- helm/cas-ciip-portal/templates/cron-prod-test-restore.yaml
- helm/cas-ciip-portal/templates/pvc-prod-backup.yaml
- helm/cas-ciip-portal/values-wksv3k-test.yaml
- helm/cas-ciip-portal/values.yaml
WIP
Ephemeral storage?:
https://kubernetes.io/blog/2020/01/21/csi-ephemeral-inline-volumes/
https://kubernetes-csi.github.io/docs/csi-driver-object.html
> prod-test restore cron-job

- helm/cas-ciip-portal/values-wksv3k-test.yaml
> Update site notice on test showing test reporter account

- app/components/Layout/Header.tsx
Removes media query listener causing serious page-level error sitewide on Safari.
> fix: Error on Safari in header

- app/containers/Organisations/Organisations.tsx
- Fixes by removing all orgs from the dropdown to which the user has requested access.
[GGIRCS-1463](https://youtrack.button.is/issue/GGIRCS-1463)
> fix: Error on requesting access to an org twice

- app/components/LegalDisclaimerText.tsx
- app/pages/certifier/certification-redirect.tsx
- app/pages/certifier/certify.tsx
- app/pages/reporter/new-application-disclaimer.tsx
- app/tests/unit/components/__snapshots__/LegalDisclaimerText.test.tsx.snap
- app/tests/unit/pages/__snapshots__/certification-redirect.test.tsx.snap
- app/tests/unit/pages/reporter/__snapshots__/new-application-disclaimer.test.tsx.snap
Legal text updates, per [GGIRCS-1705](https://youtrack.button.is/issue/GGIRCS-1705):
- `/certifier/certification-redirect` certification redirect page
- `/reporter/new-application-disclaimer` interstitial disclaimer upon starting a new application
- `/certifier/certify` individual certification page
> Legal text update

- app/containers/Organisations/UserOrganisation.tsx
- Refetch Organisations query after `createUserOrganisationMutation`.
[GGIRCS-1463](https://youtrack.button.is/issue/GGIRCS-1463)
> fix: Immediately remove requested org from access dropdown

- app/components/LegalDisclaimerText.tsx
- app/tests/unit/components/__snapshots__/LegalDisclaimerText.test.tsx.snap
Corrects some missed text from [GGIRCS-1705](https://youtrack.button.is/issue/GGIRCS-1705)
> fix: Correct legal typos

- app/package.json
- app/server/index.js
- app/yarn.lock
Did not add the recommended options that affect the generated graphql schema
> feat: use recommended postgraphile options in development and production

- app/server/index.js
See https://hackernoon.com/graceful-shutdown-in-nodejs-2f8f59d1c357 re cleanly shutting down the server.
This should prevent some of our flaky end to end CI failures
> feat: disable graphile worker signal handling and add SIGTERM listeners

- helm/cas-ciip-portal/Chart.yaml
- helm/cas-ciip-portal/templates/cron-acme-renewal.yaml
This will be coupled with an airflow DAG that will trigger
this job on a daily schedule
> feat: add cron job template to renew https certificate

- app/containers/Applications/ApplyButtonContainer.tsx
- disables apply button on click
> fix: disable apply button on click

- helm/cas-ciip-portal/templates/cron-app-users.yaml
-adds ggircs_portal schema to read-only user's priviliges in app-users cronjob
> fix: metabase access to ggircs_portal schema

- app/components/Application/ApplicationOverrideJustification.tsx
- app/components/Application/ApplicationOverrideNotificationCard.tsx
- app/containers/Applications/ApplicationWizardConfirmation.tsx
- app/cypress/integration/application-form-validation.spec.js
- app/layouts/default-layout.tsx
- app/mutations/application/updateApplicationRevisionMutation.ts
- app/pages/analyst/application-review.tsx
- app/pages/certifier/certify.tsx
- app/server/schema.graphql
- app/server/schema.json
- app/tests/integration/__snapshots__/Storyshots.test.ts.snap
- app/tests/unit/components/ApplicationOverrideJustification.test.tsx
- app/tests/unit/components/ApplicationOverrideNotificationCard.test.tsx
- app/tests/unit/components/__snapshots__/ApplicationOverrideJustification.test.tsx.snap
- app/tests/unit/components/__snapshots__/ApplicationOverrideNotificationCard.test.tsx.snap
- app/tests/unit/containers/Applications/ApplicationWizardConfirmation.test.tsx
- app/tests/unit/containers/Applications/__snapshots__/ApplicationDetailsPdf.test.tsx.snap
- app/tests/unit/containers/Applications/__snapshots__/ApplicationWizardConfirmation.test.tsx.snap
- app/tests/unit/layout/__snapshots__/default-layout.test.tsx.snap
- app/tests/unit/pages/__snapshots__/application-review.test.tsx.snap
- app/tests/unit/pages/__snapshots__/certify.test.tsx.snap
- app/tests/unit/pages/application-review.test.tsx
- app/tests/unit/pages/certify.test.tsx
- schema/data/prod/form_json/administration.json
- schema/deploy/tables/application_revision_001.sql
- schema/revert/tables/application_revision_001.sql
- schema/sqitch.plan
- schema/verify/tables/application_revision_001.sql
[GGIRCS-1391](https://youtrack.button.is/issue/GGIRCS-1391)
- Adds a column to the application_revision table (override_justification)
- Override option on summary page
- Active override notification added to both the certify & application-review pages
- Jest tests
> Override and justify application validation errors

- docs/stack.md
Placing this documentation into the correct repo.
> adding stack documentation to ciip portal doc dir

- helm/cas-ciip-portal/Chart.yaml
- helm/cas-ciip-portal/templates/cron-app-users.yaml
- schema/deploy/database_functions/read_only_user_policies.sql
- schema/revert/database_functions/read_only_user_policies.sql
- schema/sqitch.plan
- schema/verify/database_functions/read_only_user_policies.sql
- adds a function that applies select policies to all tables for a specified user
- adds a cronjob that calls the policies function
> Fix: read only user policies

- app/containers/Applications/ApplicationWizardConfirmation.tsx
- app/tests/unit/containers/Applications/ApplicationWizardConfirmation.test.tsx
- app/tests/unit/containers/Applications/__snapshots__/ApplicationWizardConfirmation.test.tsx.snap
- Adds better notification messages about certification or adds them where they were missing in the summary page
> Fix: "request sent to certifier" notification

- schema/deploy/computed_columns/application_revision_ciip_incentive.sql
- schema/deploy/computed_columns/application_revision_ciip_incentive@v1.4.0.sql
- schema/revert/computed_columns/application_revision_ciip_incentive@v1.4.0.sql
- schema/sqitch.plan
- schema/test/unit/computed_columns/application_revision_ciip_incentive_test.sql
- schema/verify/computed_columns/application_revision_ciip_incentive@v1.4.0.sql
- incentive function was throwing exceptions on values that can now be submitted via an override, the exceptions have been removed for now until we can re-think how to handle those errors & report them to the analyst.
> fix: remove incentive exceptions

- schema/deploy/views/ciip_admin.sql
- schema/revert/views/ciip_admin.sql
- schema/sqitch.plan
- schema/test/unit/views/ciip_admin_test.sql
- schema/verify/views/ciip_admin.sql
adds a view for the admin data collected in ciip (for use in metabase)
> feat: admin view

- app/containers/Applications/ApplicationDetailsCardItem.tsx
- app/containers/Forms/Form.tsx
- app/cypress/integration/application-form-validation.spec.js
- app/functions/customTransformErrors.ts
- app/tests/unit/containers/Applications/__snapshots__/ApplicationDetailsCardItem.test.tsx.snap
Explicitly shows the format required for format errors in the summary page
> Feat: explicit error messages

- app/containers/Facilities/FacilitiesRowItemContainer.tsx
- app/tests/unit/containers/Facility/FacilitiesRowItemContainer.test.tsx
- app/tests/unit/containers/Facility/__snapshots__/FacilitiesRowItemContainer.test.tsx.snap
adds a (Pending Certification) note to the draft state of an application if a certifierUrl exists for that draft.
> Feat: pending certification state

- app/components/SearchTableLayout.tsx
- app/tests/unit/components/SearchTableLayout.test.tsx
- app/tests/unit/components/__snapshots__/SearchTableLayout.test.tsx.snap
- adds a message if the search table result is empty
- adds some unit tests for SearchTableLayout
> Feat: empty search table result message

- app/components/SearchTable.tsx
- app/components/SearchTableLayout.tsx
- app/components/SelectReportingYearDropdown.tsx
- app/containers/Facilities/FacilitiesListContainer.tsx
- app/cypress/integration/reporter-select-reporting-year.spec.js
- app/pages/reporter/facilities.tsx
- app/server/schema.graphql
- app/server/schema.json
- app/tests/unit/components/__snapshots__/SearchTableLayout.test.tsx.snap
- app/tests/unit/containers/Facility/FacilitiesListContainer.test.tsx
- app/tests/unit/containers/Facility/__snapshots__/FacilitiesListContainer.test.tsx.snap
- docs/stack.md
- schema/deploy/search_functions/search_all_facilities@v1.5.0.sql
- schema/revert/search_functions/search_all_facilities.sql
- schema/revert/search_functions/search_all_facilities@v1.5.0.sql
- schema/sqitch.plan
- schema/test/unit/search_functions/function_search_all_facilities_test.sql
- schema/verify/search_functions/search_all_facilities.sql
- schema/verify/search_functions/search_all_facilities@v1.5.0.sql
- updates search_all_facilities function to filter on reporting_year
- updates relay query variables
- adds select 'Reporting Period' UI as per design in https://youtrack.button.is/issue/GGIRCS-1917
> Feat: select reporting year

- app/containers/Applications/ApplicationCommentsContainer.tsx
Fixes [GGIRCS-1948](https://youtrack.button.is/issue/GGIRCS-1948)
> fix: Always show reviewer comments regardless of revision status

- app/containers/Facilities/FacilitiesRowItemContainer.tsx
- app/tests/unit/containers/Facility/FacilitiesRowItemContainer.test.tsx
- app/tests/unit/containers/Facility/__snapshots__/FacilitiesRowItemContainer.test.tsx.snap
- Fixes application status pill still showing (Pending Certification) after an application has been certified.
- Now shows (Certified) in that case.
> Fix: inaccurate certification status

- app/containers/Applications/ApplicationListContainer.tsx
- app/tests/unit/containers/Applications/__snapshots__/ApplicationListContainer.test.tsx.snap
- fixed: search column was set to id of query rather than id of application
> fix: search/sort by application id

- app/components/Benchmark/PastBenchmarks.tsx
- app/containers/Admin/ReportingYear/NewReportingYearFormDialog.tsx
- app/containers/Admin/ReportingYear/ReportingYearFormDialog.tsx
- app/containers/Admin/ReportingYear/ReportingYearTable.tsx
- app/containers/Admin/ReportingYear/reportingYearValidation.ts
- app/containers/Applications/ApplicationCommentsByForm.tsx
- app/containers/Applications/ApplicationRowItemContainer.tsx
- app/containers/Certifier/CertificationRequestsContainer.tsx
- app/containers/KeyDates.tsx
- app/containers/Products/ProductRowItemContainer.tsx
- app/containers/RegistrationLoginButtons.tsx
- app/functions/formatDates.ts
- app/pages/certifier/certification-redirect.tsx
- app/tests/unit/containers/Applications/ApplicationCommentsByForm.test.tsx
- app/tests/unit/containers/Applications/ApplicationRowItemContainer.test.tsx
- app/tests/unit/containers/Applications/__snapshots__/ApplicationCommentsByForm.test.tsx.snap
- app/tests/unit/containers/Applications/__snapshots__/ApplicationRowItemContainer.test.tsx.snap
- Change UTC format dates to readable format
> Feat: readable dates

- app/containers/Applications/ApplicationWizard.tsx
- app/containers/Applications/ApplicationWizardStep.tsx
- app/containers/Forms/Form.tsx
- app/containers/Forms/FormSharedStyles.tsx
- app/cypress/integration/application-form-validation.spec.js
- app/tests/integration/Forms/__snapshots__/Form.test.tsx.snap
- app/tests/unit/containers/Forms/Form.test.tsx
- app/tests/unit/containers/Forms/__snapshots__/Form.test.tsx.snap
- app/tests/unit/containers/ReportingYear/__snapshots__/NewReportingYearFormDialog.test.tsx.snap
- app/tests/unit/containers/ReportingYear/__snapshots__/ReportingYearFormDialog.test.tsx.snap
- Update Form buttons to match UX suggestions in https://youtrack.button.is/issue/GGIRCS-1625
> Feature: save & exit/continue buttons

- docs/stack.md
- documents the reason behind creating _status tables, types and computed columns
> docs: _status documentation

- app/containers/Products/ProductListContainer.tsx
- app/containers/Products/ProductRowItemContainer.tsx
- app/tests/unit/containers/Products/__snapshots__/productListContainer.test.tsx.snap
- app/tests/unit/containers/Products/__snapshots__/productRowItemContainer.test.tsx.snap
In `/admin/products-benchmarks`:
- Left-aligns product names
- Capitalizes CIIP in "CIIP Benchmarked"
- Product status presented as a pill badge instead of plain text
- Vertically centers row field text
[GGIRCS-1628](https://youtrack.button.is/issue/GGIRCS-1628)
> Manage Products styling updates

- app/components/SearchTableLayout.tsx
- app/components/SortableTableHeader.tsx
- app/tests/unit/components/__snapshots__/SearchTableLayout.test.tsx.snap
- Positions sorting icons in SearchTable header to right of column labels
- For consistency, "Select All" checkbox is also positioned to right of column label (eg: in `/certifier/requests`)
[GGIRCS-2017](https://youtrack.button.is/issue/GGIRCS-2017)
> Position SearchTable header sort icons

- app/components/Forms/ApplicationFormNavbar.tsx
- app/components/Forms/ProblemReportField.tsx
- app/components/helpers/SavingIndicator.tsx
- app/containers/Forms/EmissionField.tsx
- app/containers/Forms/EmissionGasFields.tsx
- app/containers/Forms/Form.tsx
- app/containers/Forms/FormFieldTemplate.tsx
- app/containers/Forms/FormSharedStyles.tsx
- app/containers/Products/ProductCreatorContainer.tsx
- app/cypress/integration/application-form-validation.spec.js
- app/tests/unit/components/Forms/__snapshots__/ProblemReportField.test.tsx.snap
- app/tests/unit/containers/Forms/Form.test.tsx
- app/tests/unit/containers/Forms/__snapshots__/Form.test.tsx.snap
- app/tests/unit/containers/ReportingYear/__snapshots__/NewReportingYearFormDialog.test.tsx.snap
- app/tests/unit/containers/ReportingYear/__snapshots__/ReportingYearFormDialog.test.tsx.snap
- app/tests/unit/containers/User/__snapshots__/UserForm.test.tsx.snap
In the Create Product form at `/admin/products-benchmarks`, and now in the CIIP application form at `/reporter/application` as well:
- Grey background color for form
- Darker border color
- Form card has more padding
- Close button is grey instead of red
- Card header is blue with white text instead of grey
- "help" text color has been darkened to maintain AA contrast after background color change
[GGIRCS-1629](https://youtrack.button.is/issue/GGIRCS-1629)
> Create Product style update

- .github/workflows/commitlint.yml
- lint commit messages (https://github.com/marketplace/actions/commit-linter)
> ci(commitlint): add commitlint github action into ci

- app/Dockerfile
- app/containers/Applications/ApplicationDetailsContainer.tsx
- app/package.json
- app/server/index.js
- app/server/routes/print-pdf.js
- app/tests/unit/containers/Applications/__snapshots__/ApplicationDetailsContainer.test.tsx.snap
- app/yarn.lock
There is work in progress to fix the rendering with weasyprint, as Puppeteer cannot be deployed safely to OpenShift.
> Revert addition of puppeteer and temporarily disable pdf button

- helm/cas-ciip-portal/values-wksv3k-test.yaml
[GGIRCS-2040](https://youtrack.button.is/issue/GGIRCS-2040)
> Update test reporter username in site banner

- schema/deploy/tables/reporting_year_001.sql
- schema/deploy/trigger_functions/protect_date_overlap.sql
- schema/revert/tables/reporting_year_001.sql
- schema/revert/trigger_functions/protect_date_overlap.sql
- schema/sqitch.plan
- schema/test/unit/tables/reporting_year_test.sql
- schema/test/unit/trigger_functions/protect_date_overlap_test.sql
- schema/verify/tables/reporting_year_001.sql
- schema/verify/trigger_functions/protect_date_overlap.sql
- Throws an exception if a new or updated date range overlaps with other entries in the table
> feat: Protect reporting_year date ranges with trigger

- schema/sqitch.plan
sqitch.plan lines that are deployed to prod are immutable
> fix: revert sqitch.plan bug introduced in 1b5542

- app/cypress/integration/accessibility/certifier-all-pages-accessibility.spec.js
- app/cypress/integration/accessibility/reporter-all-pages-accessibility.spec.js
- app/cypress/integration/admin-access-all-pages.spec.js
- app/cypress/integration/analyst-access-all-pages.spec.js
- app/cypress/integration/analyst-diffing.spec.js
- app/cypress/integration/application-form-validation.spec.js
- app/cypress/integration/application-production.spec.js
- app/cypress/integration/email.spec.js
- app/cypress/integration/form-errors-prevent-submit.spec.js
- app/cypress/integration/login-redirects.spec.js
- app/cypress/integration/override-justification.spec.js
- app/cypress/integration/page-access.spec.js
- app/cypress/integration/product-benchmark.spec.js
- app/cypress/integration/reporter-access-all-pages.spec.js
- app/cypress/integration/reporter-certifier-access.spec.js
- app/cypress/integration/reporter-select-reporting-year.spec.js
- app/cypress/support/commands.js
PR to fix the race condition when using mock logins
> fix: cypress e2e race conditions

- helm/cas-ciip-portal/templates/networkSecurityPolicies/metabase-to-ciip-db-nsp.yaml
- helm/cas-ciip-portal/values.yaml
adds a missing nsp that allows metabase to communicate with the ciip-portal database
> fix: missing metabase nsp

- .circleci/config.yml
- app/cypress/integration/accessibility/certifier-all-pages-accessibility.spec.js
- app/cypress/integration/index.spec.js
- app/cypress/integration/reporter-certifier-access.spec.js
- app/cypress/integration_mocks/reporter-certifier-access.spec.js
- schema/data/fixtures/index-setup.sql
Mocking time on some cypress tests to avoid happo diffs due to dates being different
> fix: cypress time mock and syntax

- schema/data/prod/fuel.sql
Archived other Flared Natural Gas fuels
> feat: rename Flared Natural Gas CH4 to "Flared Natural Gas"

- app/containers/Applications/ApplicationDetailsContainer.tsx
- app/containers/Applications/ApplicationRevisionStatusContainer.tsx
- app/containers/Applications/ApplicationRowItemContainer.tsx
- app/containers/Facilities/FacilitiesRowItemContainer.tsx
- app/cypress/integration/email.spec.js
- app/lib/text-transforms.js
- app/tests/unit/containers/Applications/ApplicationStatusContainer.test.tsx
- app/tests/unit/containers/Applications/__snapshots__/ApplicationDetailsContainer.test.tsx.snap
- app/tests/unit/containers/Applications/__snapshots__/ApplicationRowItemContainer.test.tsx.snap
- app/tests/unit/containers/Applications/__snapshots__/ApplicationStatusContainer.test.tsx.snap
- app/tests/unit/containers/Facility/FacilitiesRowItemContainer.test.tsx
- app/tests/unit/containers/Facility/__snapshots__/FacilitiesRowItemContainer.test.tsx.snap
[GGIRCS-2195](https://youtrack.button.is/issue/GGIRCS-2195)
> Clean up language on application review page

- helm/cas-ciip-portal/templates/networkPolicies/mailhog-ingress.yaml
Mailhog needs its own NetworkPolicy to allow ciip_portal smtp connections in
> feat: allowing mailhog pod to get connections in

- app/components/SubmitApplication.tsx
- app/containers/Applications/ApplicationRowItemContainer.tsx
- app/containers/Applications/ApplyButtonContainer.tsx
- app/containers/Applications/ReviseApplicationButtonContainer.tsx
- app/containers/Certifier/CertificationRequestsContainer.tsx
- app/containers/Forms/Form.tsx
- app/pages/reporter/complete-submit.tsx
- app/tests/unit/containers/Applications/__snapshots__/ApplicationRowItemContainer.test.tsx.snap
- app/tests/unit/containers/Applications/__snapshots__/ApplyButtonContainer.test.tsx.snap
- app/tests/unit/containers/Applications/__snapshots__/ReviseApplicationButtonContainer.test.tsx.snap
- app/tests/unit/containers/Forms/__snapshots__/Form.test.tsx.snap
+ Changed the "submit application" button so that it is not wrapped in a Link, since the redirection already happens after the mutation succeeds
> nextjs links should pass the href to child if it is a Button 

- app/containers/Applications/ApplyButtonContainer.tsx
- app/cypress/integration/reporter-access-all-pages.spec.js
- app/cypress/integration/reporter-facilities-list.spec.js
- app/tests/unit/containers/Applications/__snapshots__/ApplyButtonContainer.test.tsx.snap
One last button to make into a real link, following [GGIRCS-2226](https://youtrack.button.is/issue/GGIRCS-2226).
> fix: Make the 'Resume application' button a real anchor link

- app/server/schema.graphql
- schema/deploy/mutations/create_fuel_naics_mutation.sql
- schema/deploy/mutations/create_naics_mutation.sql
- schema/deploy/tables/fuel_naics.sql
- schema/deploy/tables/naics.sql
- schema/revert/mutations/create_fuel_naics_mutation.sql
- schema/revert/tables/fuel_naics.sql
- schema/sqitch.plan
- schema/test/unit/mutations/create_fuel_naics_mutation_test.sql
- schema/test/unit/mutations/create_naics_mutation_test.sql
- schema/test/unit/tables/fuel_naics_test.sql
- schema/verify/mutations/create_fuel_naics_mutation.sql
- schema/verify/tables/fuel_naics.sql
- Creates the fuel_naics through-table for fuel-naics relationships
- Creates a custom mutation to upsert on conflict(fuel_id, naics_id)
- pgTap tests
> Feat: fuel naics relationship table

- app/server/schema.graphql
- schema/deploy/tables/naics_code.sql
The xls file on gov teams has both a category (description) and a ciip_sector column. This PR adds a ciip_sector column to the table
> refactor: add ciip_sector column

- app/containers/Products/ProductRowItemContainer.tsx
- app/tests/unit/containers/Products/__snapshots__/productRowItemContainer.test.tsx.snap
Fixes layout bug in [GGIRCS-2330](https://youtrack.button.is/issue/GGIRCS-2330).
> Minor cosmetic fix: Add empty column to manage products table

- schema/deploy/swrs_functions/get_carbon_tax_data.sql
- schema/deploy/swrs_functions/get_carbon_tax_data@v2.0.0.sql
- schema/revert/swrs_functions/get_carbon_tax_data@v2.0.0.sql
- schema/sqitch.plan
- schema/test/unit/swrs_functions/get_carbon_tax_data_test.sql
- schema/verify/swrs_functions/get_carbon_tax_data@v2.0.0.sql
use swrs.fuel_charge fuel_carbon_tax_details_id fkey instead of fuel_mapping_id
> refactor: update get carbon tax data

- schema/data/prod/form_json/administration.json
https://youtrack.button.is/issue/GGIRCS-1827
Customising the email format error message.
> fix: improve email validation message

- app/containers/Facilities/FacilitiesListContainer.tsx
- app/pages/reporter/facilities.tsx
- app/server/schema.graphql
- app/tests/unit/containers/Facility/FacilitiesListContainer.test.tsx
- app/tests/unit/containers/Facility/__snapshots__/FacilitiesListContainer.test.tsx.snap
- schema/deploy/queries/default_displayed_reporting_year.sql
- schema/deploy/queries/facility_application_by_reporting_year.sql
- schema/deploy/queries/facility_application_by_reporting_year@v2.0.0.sql
- schema/revert/queries/default_displayed_reporting_year.sql
- schema/revert/queries/facility_application_by_reporting_year.sql
- schema/revert/queries/facility_application_by_reporting_year@v2.0.0.sql
- schema/sqitch.plan
- schema/test/unit/queries/default_displayed_reporting_year_test.sql
- schema/test/unit/queries/facility_application_by_reporting_year_test.sql
- schema/verify/queries/default_displayed_reporting_year.sql
- schema/verify/queries/facility_application_by_reporting_year@v2.0.0.sql
or the previous one if there is no open reporting year
> feat: facilities page defaults to the current reporting year

- app/components/ProgressStepIndicator.tsx
- app/components/helpers/StatusBadgeColor.tsx
- app/containers/Organisations/Organisations.tsx
- app/cypress/integration/reporter-access-all-pages.spec.js
- app/pages/reporter/facilities.tsx
- app/pages/reporter/index.tsx
- app/tests/unit/components/ProgressStepIndicator.test.tsx
- app/tests/unit/components/__snapshots__/ProgressStepIndicator.test.tsx.snap
- app/tests/unit/containers/Organisation/__snapshots__/Organisations.test.tsx.snap
- app/tests/unit/pages/reporter/__snapshots__/facilities.test.tsx.snap
- app/tests/unit/pages/reporter/__snapshots__/index.test.tsx.snap
- app/tests/unit/pages/reporter/facilities.test.tsx
Adding a static indicator for the application process, reusing the `ProgressStepIndicator` component.
> Feat: facility application progress

- app/components/FilterableTable/Filters/ApplicationStatusFilter.tsx
- app/components/FilterableTable/Filters/EnumFilter.tsx
- app/components/FilterableTable/Filters/TableFilter.tsx
- app/containers/Facilities/FacilitiesListContainer.tsx
- app/tests/unit/containers/Facility/__snapshots__/FacilitiesListContainer.test.tsx.snap
https://youtrack.button.is/issue/GGIRCS-2407
- enum table filters not sortable
https://youtrack.button.is/issue/GGIRCS-2409
- facilityBcghgid uses includes postgraphile filter
> fix: facilityBcghgid includes and enum sort false

- app/containers/Forms/SummaryFormFieldTemplate.tsx
- app/cypress/integration/application-form-validation.spec.js
- app/package.json
- app/yarn.lock
since @rjsf/core v2.5.0, the formData is directly available in a FormFieldTemplate
> fix: restore disableRenderingIfEmpty ui schema option support

- app/tests/unit/components/FilterableTable/FilterableTableFilterRow.test.tsx
- app/tests/unit/components/FilterableTable/__snapshots__/FilterableTableFilterRow.test.tsx.snap
- app/tests/unit/components/helpers/Toaster.test.tsx
- app/tests/unit/containers/Admin/ApplicationReview/ReviewSidebar.test.tsx
- app/tests/unit/containers/Admin/ReportingYear/reportingYearValidation.test.ts
this PR removes a few harmless console log messages thrown during our frontend unit test suite
> Tech Debt: unit test error messages

- app/containers/KeyDates.tsx
Very small change, just un-commented the code we commented out a few months ago
> chore: re-add key dates to landing page

- app/cypress/integration/email.spec.js
- app/server/emailTemplates/amendment.js
- app/server/emailTemplates/applicationDecision.js
- app/server/emailTemplates/confirmation.js
- app/server/emailTemplates/notifyAdminApplicationSubmitted.js
- app/server/emailTemplates/notifyAdminOrganisationAccess.js
- app/server/emailTemplates/organisationAccessApproved.js
- app/server/emailTemplates/requestForOrganisationAccess.js
- app/server/emailTemplates/welcome.js
- app/server/tasks/sendMail.js
Updates all transactional email text and subject lines to new messages for this year.
[GGIRCS-2248](https://youtrack.button.is/issue/GGIRCS-2248)
> Updated email templates and subject lines

- README.md
- app/components/Incentives/IncentiveSegmentFormula.tsx
- app/containers/Organisations/Organisations.tsx
- app/pages/index.tsx
- app/tests/unit/containers/Organisation/__snapshots__/Organisations.test.tsx.snap
- app/tests/unit/pages/__snapshots__/index.test.tsx.snap
- schema/data/prod/form_json/administration-2020.json
- [GGIRCS-2304](https://youtrack.button.is/issue/GGIRCS-2304) Updates text blurbs in the reporter dashboard
- [GGIRCS-2208](https://youtrack.button.is/issue/GGIRCS-2208) Link to program website on the homepage
* adds a link to program website in the intro paragraph
* replaces the factsheet link at bottom of page with link to program website
- [GGIRCS-2450](https://youtrack.button.is/issue/GGIRCS-2450) Improved label for secondary contact on application page
- [GGIRCS-2209](https://youtrack.button.is/issue/GGIRCS-2209) Fixes "carbon tax payed" typo in incentive formula on application review page
> Last few text updates for 2021

- README.md
- app/containers/RegistrationLoginButtons.tsx
- app/functions/formatDates.ts
- app/tests/unit/containers/RegistrationLoginButtons.test.tsx
- app/tests/unit/containers/__snapshots__/RegistrationLoginButtons.test.tsx.snap
- Uncomments additional place where deadline is shown on homepage (right above Login/Register button) [GGIRCS-2441](https://youtrack.button.is/issue/GGIRCS-2441)
- Removes link to defunct PDF from README [GGIRCS-2208](https://youtrack.button.is/issue/GGIRCS-2208)
> Homepage deadline

- app/.postgraphilerc.js
- app/containers/Forms/ProductRowIdField.tsx
- app/server/index.js
- app/server/schema.graphql
- app/tests/unit/containers/Forms/ProductRowIdField.test.tsx
- app/tests/unit/containers/Forms/__snapshots__/ProductRowIdField.test.tsx.snap
this PR
- enables filtering through relations in postgraphile
- fixes the issue where reporters could still report deleted products for the naics code
> Fix: deleted naics product associations are allowed in the form

- app/package.json
- app/tests/unit/components/Admin/__snapshots__/NaicsCodeSelectionComponent.test.tsx.snap
- app/tests/unit/components/FilterableTable/Filters/__snapshots__/ApplicationStatusFilter.test.tsx.snap
- app/tests/unit/components/FilterableTable/__snapshots__/FilterableTable.test.tsx.snap
- app/tests/unit/components/FilterableTable/__snapshots__/FilterableTableFilterRow.test.tsx.snap
- app/tests/unit/components/__snapshots__/AddOrganisationModal.test.tsx.snap
- app/tests/unit/components/__snapshots__/ProgressStepIndicator.test.tsx.snap
- app/tests/unit/components/products/__snapshots__/MissingProductsComponent.test.tsx.snap
- app/tests/unit/containers/Admin/ProductNaicsCode/__snapshots__/AllowableProductsSearch.test.tsx.snap
- app/tests/unit/containers/Admin/ProductNaicsCode/__snapshots__/ProductNaicsCodeAssociation.test.tsx.snap
- app/tests/unit/containers/Applications/__snapshots__/ApplicationReviewValidationContainer.test.tsx.snap
- app/tests/unit/containers/Forms/__snapshots__/NaicsField.test.tsx.snap
- app/tests/unit/containers/Products/productRowItemContainer.test.tsx
- app/yarn.lock
fixing CVEs:
npm # 1751: https://nvd.nist.gov/vuln/detail/CVE-2020-28469, 
npm # 1753: https://nvd.nist.gov/vuln/detail/CVE-2021-33623,
npm # 1754: https://nvd.nist.gov/vuln/detail/CVE-2021-33587
> Chore: june 6 CVEs

- app/containers/Forms/EmissionField.tsx
- app/containers/Forms/Form.tsx
- app/tests/unit/containers/Forms/__snapshots__/Form.test.tsx.snap
Fixes the issue where the emissions form (and any other form) width would shrink depending on its content.
Added a `<Row><Col md={12}>...` to enforce the content matching the form width.
This is most visible when the emissions form has no data reported and the "hide" button is clicked
> Fix: emission form width

- app/components/Application/ApplicationOverrideJustification.tsx
- app/components/SubmitApplication.tsx
- app/components/helpers/LoadingOnClickButton.tsx
- app/containers/Applications/ApplicationConsent.tsx
- app/containers/Organisations/Organisations.tsx
- app/containers/Products/ProductCreatorContainer.tsx
- app/containers/Products/ProductCreatorForm.tsx
- app/lib/withPromiseLoading.tsx
- app/tests/unit/components/ApplicationOverrideJustification.test.tsx
- app/tests/unit/components/__snapshots__/ApplicationOverrideJustification.test.tsx.snap
- app/tests/unit/components/helpers/LoadingOnClickButton.test.tsx
- app/tests/unit/components/helpers/__snapshots__/LoadingOnClickButton.test.tsx.snap
- app/tests/unit/lib/withPromiseLoading.test.tsx
creating a higher order component to wrap mutation calls and allowing components to react to the state of that mutation (in flight or not).
This refactors:
- the ProductCreator form
- the buttons on the Reporter side, except the "Save & Continue" of the form
> Tech Debt: refactor network triggers (Reporter)

- app/containers/Applications/ApplicationDetailsCardItem.tsx
- app/containers/Forms/Form.tsx
- app/containers/User/UserForm.tsx
- app/functions/customTransformErrors.ts
- app/tests/unit/containers/User/UserForm.test.tsx
- app/tests/unit/containers/User/__snapshots__/UserForm.test.tsx.snap
validates the email and phone number fields on registration.
> Fix: registration page validation

- .github/ISSUE_TEMPLATE/bug-template.md
- .github/ISSUE_TEMPLATE/task-issue-template.md
Created task template & bug template
> Update issue templates

- schema/deploy/views/ciip_incentive_per_facility.sql
- schema/revert/views/ciip_incentive_per_facility.sql
- schema/sqitch.plan
- schema/test/unit/views/ciip_incentive_per_facility_test.sql
- schema/verify/views/ciip_incentive_per_facility.sql
A view that shows the total ciip incentive information for each submitted application, based on the latest submitted version
> Feat: ciip incentive per facility view

- dags/cas_ciip_portal_dags.py
- don't use env var ENVIRONMENT
> fix: check namespace suffix for env

- app/containers/Applications/ApplicationWizardConfirmation.tsx
- app/tests/unit/containers/Applications/ApplicationWizardConfirmation.test.tsx
- app/tests/unit/containers/Applications/__snapshots__/ApplicationWizardConfirmation.test.tsx.snap
Submit button was hidden for all older applications. Should have only been hidden for older applications with version <= 1
> Fix: show submit button

- schema/Makefile
- schema/test/style/column_test.sql
- schema/test/style/materialized_view_test.sql
- schema/test/style/operational_test.sql
- schema/test/style/schema_test.sql
- schema/test/style/table_test.sql
- schema/test/style/variable_test.sql
Define the schemas to test in the makefile with `--set` and use variables inside the style tests.
> test: define style test schemas in makefile

- app/package.json
- app/server/helpers/userGroupAuthentication.js
- app/yarn.lock
> fix: redirect unauthorized idir users to /analyst/pending

- app/containers/Forms/EmissionGasFields.tsx
- app/package.json
- app/tests/unit/containers/Applications/__snapshots__/ApplicationDetailsCardItem.test.tsx.snap
- app/tests/unit/containers/Forms/__snapshots__/Form.test.tsx.snap
- app/yarn.lock
fixes CVE-2021-23566 and CVE-2022-0235
> Chore: audit fix

- app/yarn.lock
fixes CVE-2020-7751 & CVE-2020-15366
> chore: update packages

- schema/deploy/swrs_functions/get_swrs_facility_data.sql
working locally, failing on develop. I think changing select row to just 'select' may fix the issue
> chore: change 'select row' to 'select'

- app/.env.example
- app/components/Dashboard/ggircsAppLink.tsx
- app/components/Dashboard/programAdministration.tsx
- app/next.config.js
- app/package.json
- app/pages/admin/index.tsx
- app/tests/unit/components/Dashboard/__snapshots__/ggircsAppLink.test.tsx.snap
- app/tests/unit/components/Dashboard/__snapshots__/programAdministration.test.tsx.snap
- app/tests/unit/components/Dashboard/ggircsAppLink.test.tsx
- app/tests/unit/components/Dashboard/programAdministration.test.tsx
- app/tests/unit/containers/Forms/__snapshots__/FuelRowIdField.test.tsx.snap
- app/tests/unit/containers/Forms/__snapshots__/ProductRowIdField.test.tsx.snap
- app/yarn.lock
- helm/cas-ciip-portal/templates/deploy.yaml
- helm/cas-ciip-portal/values-dev.yaml
- helm/cas-ciip-portal/values-prod.yaml
- helm/cas-ciip-portal/values-test.yaml
- helm/cas-ciip-portal/values.yaml
This also fixes the metabase link being hardcoded
> Feat: link to ggircs in admin dashboard

- app/yarn.lock
CVE-2022-31129 & CVE-2021-20066
> chore: fix advisories

- app/containers/Admin/ReportingYear/NewReportingYearFormDialog.tsx
- app/containers/Admin/ReportingYear/ReportingYearFormDialog.tsx
Card: https://github.com/bcgov/cas-ciip-portal/issues/2096
> Fix: application closes 12 hours early

- app/server/middleware/user.js
- schema/deploy/policies/ciip_user_policies_003_restrict_permissions.sql
- schema/revert/policies/ciip_user_policies_003_restrict_permissions.sql
- schema/sqitch.plan
- schema/test/unit/tables/ciip_user_test.sql
- schema/verify/policies/ciip_user_policies_003_restrict_permissions.sql
recreating #2162 because of some gh actions caching issues
> Chore: update ciip user rls

- app/server/schema.graphql
- schema/data/deploy-data.sh
- schema/data/prod/fuel_emission_category.sql
- schema/deploy/tables/fuel_emission_category.sql
- schema/revert/tables/fuel_emission_category.sql
- schema/sqitch.plan
- schema/test/unit/tables/fuel_emission_category_test.sql
- schema/verify/tables/fuel_emission_category.sql
Card: https://github.com/bcgov/cas-ciip-portal/issues/2145
To check I'd correctly entered the data:
- checked that the number of inserted records (216) matched the sum of records in the spreadsheet (added up all the 1s)
- made sure that the breakdown of each category (eg 8 flaring) matched the amount of times find/replace found that category
> Create fuel_emission_category table

- helm/cas-ciip-portal/templates/cronJobs/cron-app-users.yaml
- helm/cas-ciip-portal/templates/cronJobs/cron-deploy-data.yaml
- helm/cas-ciip-portal/templates/cronJobs/cron-init-db.yaml
- helm/cas-ciip-portal/templates/cronJobs/cron-init-graphile-schema.yaml
- helm/cas-ciip-portal/templates/cronJobs/cron-load-testing-data.yaml
- helm/cas-ciip-portal/templates/cronJobs/cron-prod-test-restore.yaml
- helm/cas-ciip-portal/templates/cronJobs/cron-swrs-import.yaml
[ZH CARD](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-ciip-portal/2183)
> chore: 2183 update cronjobs schedule

- app/components/Dashboard/userManagement.tsx
- app/containers/User/ManageBceidUserTable.tsx
- app/containers/User/ManageBceidUserTableRow.tsx
- app/cypress/integration/accessibility/analyst-all-pages-accessibility.spec.js
- app/cypress/integration/analyst-access-all-pages.spec.js
- app/cypress/integration/analyst-manage-bceid-users.spec.js
- app/mutations/user/updateUserMutation.ts
- app/pages/analyst/index.tsx
- app/pages/analyst/manage-bceid-users.tsx
- app/tests/unit/containers/User/ManageBceidUserTable.test.tsx
- app/tests/unit/containers/User/ManageBceidUserTableRow.test.tsx
- app/tests/unit/containers/User/__snapshots__/ManageBceidUserTable.test.tsx.snap
- app/tests/unit/containers/User/__snapshots__/ManageBceidUserTableRow.test.tsx.snap
- app/tests/unit/pages/analyst/__snapshots__/manage-bceid-users.test.tsx.snap
- app/tests/unit/pages/analyst/manage-bceid-users.test.tsx
- schema/deploy/policies/ciip_user_policies_004_analysts_update_reporters.sql
- schema/revert/policies/ciip_user_policies_004_analysts_update_reporters.sql
- schema/sqitch.plan
- schema/test/unit/tables/ciip_user_test.sql
- schema/verify/policies/ciip_user_policies_004_analysts_update_reporters.sql
> Feat: bceid reset

- app/containers/Forms/VerificationStatement.tsx
- app/tests/unit/containers/Applications/VerificationStatement.test.tsx
- app/tests/unit/containers/Applications/__snapshots__/VerificationStatement.test.tsx.snap
[zenhub 2203](https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-ciip-portal/2203)
> feat: added verification statement alert

- .github/workflows/test.yaml
- app/tests/perf/k6-mutations.js
- app/tests/perf/parse_results.js
- app/tests/perf/run_test.sh
- app/tests/perf/test-admin.js
> chore: add smoke tests to ci

- schema/deploy/tables/incremental_fuel_charge_baseline_001.sql
- schema/revert/tables/incremental_fuel_charge_baseline_001.sql
- schema/sqitch.plan
- schema/test/unit/computed_columns/application_revision_carbon_tax_test.sql
- schema/test/unit/tables/incremental_fuel_charge_baseline_test.sql
- schema/test/unit/views/ciip_carbon_tax_calculation_test.sql
- schema/verify/tables/incremental_fuel_charge_baseline_001.sql
> Feat: update baseline charges

- app/containers/RegistrationLoginButtons.tsx
- app/tests/unit/containers/RegistrationLoginButtons.test.tsx
- app/tests/unit/containers/__snapshots__/RegistrationLoginButtons.test.tsx.snap
Updating the CIIP application open dates for the 2024 cycle
> Chore: 2268 update 2024 dates
