bcgov/cas-ciip-portal

package.json, yarn.lock
resolves:
- [CVE-2019-1010266](https://nvd.nist.gov/vuln/detail/CVE-2019-1010266)
- [CVE-2019-10744](https://nvd.nist.gov/vuln/detail/CVE-2019-10744)
- [CVE-2018-16487](https://nvd.nist.gov/vuln/detail/CVE-2018-16487)
=> force graphql-cli to use a newer version of lodash

package.json, yarn.lock
resolves:
- [CVE-2017-16024](https://nvd.nist.gov/vuln/detail/CVE-2017-16024)
=> remove dependency on sync-exec by updating npm-run

app/package.json, app/yarn.lock
There were a few missing peer dependencies and incompatible peer dependencies.
`react-relay` was updated to match `relay-runtime` and `relay-compiler`
=> Fix app node dependencies

app/containers/Organisations/UserOrganisation.js, app/mutations/user_organisation/UpdateUserOrganisation.js
Hotfix adds a delayed function that changes a user-organisation request from 'pending' to 'active' 4 seconds after creation. For demo purposes. To be removed after the demo
=> Hotfix - Set organisation request status to active on delay

app/lib/relay-environment/server.js
This removes the "cannot get function 'find' of undefined" error that flashes before rendering a page
=> fix (relay-environment): do not throw an error with undefined relayData

app/lib/relay-environment/index.js, app/package.json, app/yarn.lock
It is needed by the relay server-side rendering
=> fix: Add isomorphic-fetch as a dependency

.circleci/config.yml
It's helpful to know that the production build will compile before we
start wasting pathfinder compute resources making a deployable container
image for the revision.
=> pathfinder build should wait for next.js compilation 

app/next.config.js, app/package.json, app/yarn.lock
This leaves four available dependencies unmerged as they have breaking
changes (indicated by semver):
```
Package                     Current Wanted Latest        Package Type    URL
bootstrap                   3.4.1   3.4.1  4.3.1         dependencies    https://getbootstrap.com/
eslint-config-xo-typescript 0.19.0  0.19.0 0.21.0        devDependencies https://github.com/xojs/eslint-config-xo-typescript#readme
nock                        9.6.1   9.6.1  11.7.0        devDependencies https://github.com/nock/nock#readme
react-jsonschema-form       1.8.0   1.8.0  2.0.0-alpha.1 dependencies    https://github.com/mozilla-services/react-jsonschema-form#readme
```
^ use `yarn outdated` to verify
This closes a bunch of dependabot PRs.
=> Update all dependencies assumed to be compatible

app/.babelrc, app/components/SearchTableLayout.tsx, app/containers/Admin/OrganisationRequestsTable.tsx, app/containers/Admin/OrganisationRequestsTableRow.tsx, app/containers/Forms/Form.tsx, app/containers/Forms/FormArrayFieldTemplate.tsx, app/containers/Organisations/Facility.tsx, app/containers/User/UserForm.tsx, app/next-env.d.ts, app/package.json, app/tests/containers/Forms/__snapshots__/Form.test.tsx.snap, app/tests/pages/application-details.test.tsx, app/yarn.lock
For people using an IDE (@wenzowski nothing to see here), you may need to update the typescript version it uses. After running `yarn install` open the Facility component to see if your IDE complains about the [optional chaining](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#optional-chaining):
@hamzajaved Yours should update nicely, if not see https://www.jetbrains.com/help/webstorm/settings-languages-typescript.html
@dleard @blueQcloud @dimak1 If the root folder you have opened is `app`, you should be fine (maybe you still need the last step below). Otherwise, add the following line to your VScode workspace settings to use the Typescript in `app/node_module` instead of the one shipped with VScode (the version with Typescript 3.7 is still in beta: 
``` …
```
=> Upgrade to typescript 3.7 and add example of optional chaining

app/package.json, app/yarn.lock
Versions of handlebars prior to 4.5.3 are vulnerable to Arbitrary Code
Execution. The package's lookup helper fails to properly validate
templates, allowing attackers to submit templates that execute arbitrary
JavaScript in the system. It is due to an incomplete fix for a previous
issue. This vulnerability can be used to run arbitrary code in a server
processing Handlebars templates or on a victim's browser
(effectively serving as Cross-Site Scripting).
see https://www.npmjs.com/advisories/1324
see https://www.npmjs.com/advisories/1316
=> fix(security): patch arbitrary code execution exploit

app/package.json, app/yarn.lock
Versions of mem prior to 4.0.0 are vulnerable to Denial of Service
(DoS). The package fails to remove old values from the cache even
after a value passes its maxAge property. This may allow attackers
to exhaust the system's memory if they are able to abuse the
application logging.
see https://www.npmjs.com/advisories/1084
=> Fix(security): mem 1.1.0 is vulnerable to DoS attack; use mem >= 4.0.0

app/containers/Forms/Form.tsx, app/containers/User/UserForm.tsx, app/tests/containers/Forms/__snapshots__/Form.test.tsx.snap
See: https://github.com/rjsf-team/react-jsonschema-form/issues/1197
=> fix: enable rsjf's safeRenderCompletion hack to prevent cursor jumps

app/tsconfig.json
The includes wasn't really needed anyway as it was matching every tsx? and js files. However, I assume that typescript-eslint was listing the files/folders matching the globs when starting to watch the project, so new files were not in that list, causing it to complain about the file not being included in the project, and requiring us to restart the IDE. Now the app folder itself is included (except what is defined in the `excluded` array), so newly added files match that.
=> fix (eslint): delete includes in tsconfig to fix error on new files

app/package.json
=> fix: remove unused 'diff' dependency

app/containers/Applications/ApplicationWizard.tsx
This causes a flaky failure in end-to-end tests
=> fix: do not render ApplicationFormNavbar before setting formResultId

app/server/index.js, app/server/tasks/hello.js, app/server/tasks/sendMail.js, schema/deploy/trigger_functions/run_graphile_worker_job.sql
- set run_graphile_worker_job function as `security definer`
- change user role when running NO_AUTH flag to 'postgres' (superuser)
- fix some weird xo shenanigans that added a bunch of .js.js.js to the end of requires in worker's `tasks` folder.
=> Fix some bugs

schema/deploy/database_functions/graphile_worker_job_definer.sql, schema/deploy/trigger_functions/checksum_form_results.sql, schema/test/unit/trigger_functions/checksum_form_results_test.sql
- missing `security definer` declaration in graphile_worker_job_definer
- checksum_form_results() was updating form_result_status in place instead of inserting a new one.
=> Fix a couple backend bugs

app/containers/Applications/ApplicationRecertificationContainer.tsx, app/containers/Applications/ApplicationWizardConfirmation.tsx, app/cypress/integration/reporter-access-all-pages.spec.js, app/mutations/form/createCertificationUrl.ts, app/package.json, app/pages/certifier/certify.tsx, app/server/emailTemplates/certificationRequest.js, app/server/emailTemplates/recertificationRequest.js, app/server/emailTemplates/signedByCertifier.js, app/server/schema.graphql, app/server/schema.json, app/server/tasks/sendMail.js, app/tests/unit/containers/Applications/ApplicationWizardConfirmation.test.tsx, app/tests/unit/containers/Applications/__snapshots__/ApplicationWizardConfirmation.test.tsx.snap, app/tests/unit/pages/__snapshots__/certify.test.tsx.snap, app/tests/unit/pages/certify.test.tsx, schema/data/dev/certification_url.sql, schema/data/fixtures/reporter-all-access-setup.sql, schema/data/fixtures/reporter-all-access-teardown.sql, schema/deploy/tables/certification_url.sql, schema/deploy/trigger_functions/run_graphile_worker_job.sql, schema/test/unit/computed_columns/application_revision_certification_signature_is_valid_test.sql, schema/test/unit/trigger_functions/signature_md5_test.sql, schema/verify/tables/certification_url.sql
- Adds triggers & email templates for:
- request for certification (upon email input by reporter)
- request for re-certification (data has changed between url generation & signing)
- certifier has signed (upon certifier signing)
- Refactors URL generation in summary component -> send url to certifier email instead. (can still copy link afterwards)
=> Certifier-related email triggers

app/package.json
We have several yarn resolutions that are getting old. Just seeing what can be removed as package versions have been updated.
=> Remove outdated yarn resolutions

app/cypress/support/commands.js
The issue was generating text between the backticks (` `)  and added unexpected extra spaces in terms of code indentation.
=> fix syntax error near EOF

app/containers/Products/ProductCreatorContainer.tsx, app/containers/Products/ProductListContainer.tsx, app/containers/Products/ProductRowItemContainer.tsx, app/cypress/integration/product-benchmark.spec.js, app/mutations/product/createProductMutation.ts, app/pages/admin/products-benchmarks.tsx, app/tests/unit/containers/Products/__snapshots__/productListContainer.test.tsx.snap, app/tests/unit/containers/Products/productListContainer.test.tsx
- refresh products on create new product
- refresh products on edit product/benchmark
- add cypress test
The allProducts -> totalCount update is a bit of a hack, It's triggering the refetch function with a new variable so that the whole refetch fires. It appears we are breaking the 'relay way' of doing things with the current way the search functions work. This is the way it has been done for facilitiesList as well.
=> Reload products page

app/containers/Facilities/FacilitiesListContainer.tsx, app/pages/reporter/facilities-list.tsx, app/server/schema.graphql, app/server/schema.json, app/tests/unit/containers/Facility/FacilitiesListContainer.test.tsx, app/tests/unit/containers/Facility/__snapshots__/FacilitiesListContainer.test.tsx.snap, schema/deploy/search_functions/search_all_facilities.sql, schema/deploy/types/facility_search_result.sql
- Add an offset value to search_all_facilities.sql
- Add Pagination element to facilitiesListContainer & use to update offset value
- Return a 'totalFacilitiesCount' value along with search results to dynamically render pagination buttons
- I did some exploring of paginating the 'relay way' but it really does focus on the facebook infinite scroll style of pagination. The way the search function works also breaks the cursor-based pagination a bit, as we are not querying a table, but creating results on the fly, assigning id's by row_number() & returning them from the search function.
=> Paginate Facilities

app/containers/Facilities/FacilitiesListContainer.tsx, app/containers/Products/product-schema.json, app/tests/unit/containers/Facility/FacilitiesListContainer.test.tsx, app/tests/unit/containers/Facility/__snapshots__/FacilitiesListContainer.test.tsx.snap, schema/deploy/tables/facility.sql
- Show no more than 9 pages in the pagination bar with ellipsis indicating there are more pages ahead/behind active page
- Add tests
- Fix a typo/bad grammar in the help widget for 'requiresProductAmount'
=> Truncate facilities pagination bar

.czrc, .gitlint, .pre-commit-config.yaml, Makefile, app/package.json, app/yarn.lock, docs/developer-guide.md, requirements.txt
[![git_commit_2x](https://user-images.githubusercontent.com/597920/67593880-fa783080-f717-11e9-8423-cf1319cb70fc.png)](https://xkcd.com/1296/)
**Developer action is required to enable this feature locally.**
The `commit-msg` hook must be installed to ensure commit messages
conform to community standards:
```bash
pre-commit install --hook-type commit-msg
```
The project [pre-commit] framework configuration
has been updated to include hooks for [gitlint] and a [`.gitlint`]
configuration file has been added to control its [rules].
[pre-commit]: https://pre-commit.com/
[gitlint]: http://jorisroovers.com/gitlint/
[`.gitlint`]: http://jorisroovers.com/gitlint/configuration/
[rules]: http://jorisroovers.com/gitlint/rules/
=> Use pre-commit to verify commit message format

.circleci/config.yml, schema/deploy/schema_swrs.sql, schema/revert/schema_swrs.sql, schema/sqitch.plan, schema/verify/schema_swrs.sql
It is not dropped when reverting as it may contain
objects created by other sqitch projects, or by pg_restore.
This allows the CI schema job to only run sqitch deploy.
https://youtrack.button.is/issue/GGIRCS-1224
=> feat(schema): swrs schema is created by sqitch if not exists

app/cypress/integration/application-form-validation.spec.js, app/tests/integration/Forms/__snapshots__/Form.test.tsx.snap, app/tests/unit/containers/Applications/__snapshots__/ApplicationDetailsPdf.test.tsx.snap, schema/data/fixtures/change-form-result.sql, schema/data/fixtures/email-setup.sql, schema/data/fixtures/reporter-all-access-setup.sql, schema/data/prod/form_json/administration.json
- Implements custom format validation of BC Corporate Registry Number in the "Administration Data" section of industry reporter form:
* 1 to 3 letters followed by 7 digits
* `^[A-Za-z]{1,3}\d{7}$`
- Updates test snaphots
- Updates E2E test fixtures with correct number format
- Add integration test
=> Feature: Validate BC Corporate Registry Number format

app/package.json, app/yarn.lock
Adds missing dependency, `'babel-preset-react-app'` required by Storybook.
Related: [GGIRCS-1237](https://youtrack.button.is/issue/GGIRCS-1237)
=> Fix Storybook

app/lib/error-boundary.tsx
=> feat: error boundary shows a useful error message

app/package.json, app/yarn.lock
Removes Bootstrap (specified as 3.x) from our direct dependencies.
This project currently has two versions of Bootstrap installed:
- 3.x in our direct dependencies but not in use - made redundant by `react-bootstrap` which imports its own Bootstrap
- 4.x - required by `react-bootstrap` and is the version in use
=> Remove unused older version of Bootstrap

app/containers/Applications/ApplicationCommentsContainer.tsx, app/containers/Applications/ApplicationDetailsPdf.tsx, app/containers/Applications/ApplicationRevisionStatusContainer.tsx, app/mutations/application/createApplicationRevisionStatusMutation.ts, app/pages/analyst/application-review.tsx, app/pages/reporter/view-application.tsx, app/server/schema.graphql, app/server/schema.json, app/tests/unit/pages/__snapshots__/application-review.test.tsx.snap, app/tests/unit/pages/__snapshots__/view-application.test.tsx.snap, app/tests/unit/pages/application-review.test.tsx, app/tests/unit/pages/view-application.test.tsx, schema/deploy/computed_columns/application_application_revision_status.sql, schema/revert/computed_columns/application_application_revision_status.sql, schema/verify/computed_columns/application_application_revision_status.sql
The computed column `application_application_revision_status` was pulling the latest status for the application, where it should have been getting the status for the revision being viewed.
Resolved by adding a versionNumberInput variable to the computed column.
=> Fix: incorrect review status

app/containers/Forms/EmissionGasFields.tsx, app/package.json, app/yarn.lock
uses the 'decimal.js-light' library to properly parse decimal values.
=> Fix: javascript decimals

schema/deploy/search_functions/search_all_facilities.sql
This line was removed in #595 I'm not sure how it made it back in.
=> fix(facility): remove extra join condition on created_at column

app/containers/Applications/ApplicationWizardConfirmation.tsx, app/cypress/integration/email.spec.js, app/cypress/integration/reporter-access-all-pages.spec.js, app/server/schema.graphql, app/server/schema.json, app/tests/unit/containers/Applications/ApplicationWizardConfirmation.test.tsx, app/tests/unit/containers/Applications/__snapshots__/ApplicationWizardConfirmation.test.tsx.snap, schema/deploy/tables/certification_url.sql, schema/deploy/trigger_functions/run_graphile_worker_job.sql, schema/test/unit/tables/certification_url_test.sql, schema/verify/tables/certification_url.sql
- Add checkbox to optionally notify certifier by email
- Updates certification_url table with boolean to indicate whether to send an email
- Updates trigger function to not send email on boolean = false
- Create pgTap tests to test trigger function
- Update jest/cypress tests
=> feat(certification): Optionally email certifier

schema/data/prod/emission.sql, schema/deploy/swrs_functions/init_application_emission_form_result.sql, schema/deploy/views/ciip_carbon_tax_calculation.sql, schema/deploy/views/ciip_fuel.sql, schema/test/unit/swrs_functions/init_application_emission_form_result_test.sql, schema/test/unit/views/ciip_carbon_tax_calculation_test.sql
- Add the emission category 'Other, non-carbon taxed'
- Ignore 'Other, non-carbon taxed' in carbon-tax calculation
- Update emission init function to not include 'Other non-carbon taxed' in the form
=> feat(emisison): Non carbon taxed emission category

app/containers/Certifier/CertificationRequestsTable.tsx, app/cypress/integration/reporter-certifier-access.spec.js, app/pages/certifier/requests.tsx, app/server/schema.graphql, app/server/schema.json, app/tests/unit/pages/__snapshots__/certifier-requests.test.tsx.snap, app/tests/unit/pages/certifier-requests.test.tsx, schema/deploy/computed_columns/ciip_user_certification_requests.sql, schema/revert/computed_columns/ciip_user_certification_requests.sql, schema/sqitch.plan, schema/test/unit/computed_columns/ciip_user_certification_requests_test.sql, schema/verify/computed_columns/ciip_user_certification_requests.sql
- Adds a computed column that lists all non-expired certification requests directed to the current user (as determined by their email address).
- Adds a page at /certifer/requests` listing these requests where the certifier can click through to certify individual applications.
[GGIRCS-1393](https://youtrack.button.is/issue/GGIRCS-1393)
=> List all certification requests for current user by email

app/package.json, app/yarn.lock
- Fixes https://www.npmjs.com/advisories/1219
- I may have done a bad bad thing, or at least this is worth watching as no new version is currently available that is unaffected. So I have rolled this package back to the last unaffected version, which is a beta from a year ago.
This package is only used by storybook
=> Fix failing audit CI step

app/components/RegistrationLoginButtons.tsx, app/pages/index.tsx, app/pages/login-redirect.tsx, app/tests/unit/pages/__snapshots__/index.test.tsx.snap, app/tests/unit/pages/__snapshots__/login-redirect.test.tsx.snap, app/tests/unit/pages/login-redirect.test.tsx
- Updates the application close date in another place on the landing page, just above Register and Apply (missed in guidance doc for #667 aka. [GGIRCS-570](https://youtrack.button.is/issue/GGIRCS-570)). This date is no longer hard-coded in the copy.
- Adds a snapshot for the login-redirect page, where the above "Register and apply" component is also included.
=> Update additional date in landing page copy

app/containers/Forms/Form.tsx, app/containers/Forms/ProductField.tsx, app/containers/Products/ProductCreatorContainer.tsx, app/containers/Products/ProductRowItemContainer.tsx, app/server/schema.graphql, app/server/schema.json, app/tests/integration/Forms/__snapshots__/Form.test.tsx.snap, app/tests/unit/containers/Applications/__snapshots__/ApplicationDetailsPdf.test.tsx.snap, app/tests/unit/containers/Forms/__snapshots__/Form.test.tsx.snap, app/tests/unit/containers/Forms/__snapshots__/ProductionFields.test.tsx.snap, schema/data/prod/energy_product.sql, schema/data/prod/form_json/production.json, schema/data/test/product.sql, schema/deploy/computed_columns/application_revision_ciip_incentive.sql, schema/deploy/search_functions/search_products.sql, schema/deploy/tables/product.sql, schema/deploy/views/ciip_production.sql, schema/test/unit/computed_columns/application_revision_ciip_incentive_test.sql
- Adds a database exception in application_revision_ciip_incentive if:
- 2 products are reported where requires_emission_allocation = false AND
- Both products are non-energy products
- Adds front-end custom validation that will throw an error in the production form for the same conditions.
=> Fix: requires_emission_allocation sanity check

app/components/LegalDisclaimerText.tsx, app/pages/certifier/certify.tsx, app/pages/resources/application-disclaimer.tsx, app/tests/unit/components/LegalDisclaimerText.test.tsx, app/tests/unit/components/__snapshots__/LegalDisclaimerText.test.tsx.snap, app/tests/unit/pages/__snapshots__/application-disclaimer.test.tsx.snap, app/tests/unit/pages/application-disclaimer.test.tsx
Addendum to [GGIRCS-1517](https://youtrack.button.is/issue/GGIRCS-1517) which added a page for a CIIP-specific disclaimer. However, we want to reserve space at this URL (`/resources/disclaimer`) for the boilerplate website disclaimer from Devhub.
The CIIP-specific disclaimer will now live at `/resources/application-disclaimer` instead.
=> feat: Separate pages for CIIP application disclaimer vs. website disclaimer

app/containers/Certifier/CertificationRequestsContainer.tsx, app/containers/Facilities/FacilitiesListContainer.tsx, app/pages/certifier/requests.tsx, app/pages/reporter/facilities-list.tsx, app/server/schema.graphql, app/server/schema.json, schema/deploy/search_functions/search_all_facilities.sql, schema/deploy/search_functions/search_certification_requests.sql, schema/test/unit/search_functions/function_search_all_facilities_test.sql, schema/test/unit/search_functions/search_certification_requests_test.sql, schema/verify/search_functions/search_all_facilities.sql, schema/verify/search_functions/search_certification_requests.sql
The limit value was hardcoded in the search functions, making `maxResultsPerPage` do nothing. I've updated the search functions to use `maxResultsPerPage` as the limit in the search query.
=> fix: hardcoded limit in search functions

helm/cas-ciip-portal/templates/airflow-dag-trigger.yaml, helm/cas-ciip-portal/templates/cron-app-users.yaml, helm/cas-ciip-portal/templates/cron-deploy-data.yaml, helm/cas-ciip-portal/templates/cron-init-db.yaml, helm/cas-ciip-portal/templates/cron-init-graphile-schema.yaml, helm/cas-ciip-portal/templates/cron-swrs-import.yaml
The templates need to be updated before the airflow-dag-trigger runs
=> fix: cron charts should be pre-install/upgrade hooks

app/.well-known/Readme.md, app/server/index.js, helm/cas-ciip-portal/templates/cron-acme-issue.yaml, helm/cas-ciip-portal/templates/deploy.yaml
using the `static` directory didn't work; trying an express middleware instead
=> fix: acme requires .well-known to be accessible

app/server/index.js, helm/cas-ciip-portal/templates/cron-acme-issue.yaml, helm/cas-ciip-portal/values-wksv3k-dev.yaml
🐉🐉🐉
additionally, turns on SSL in dev & uses the issued cert
TODO: still need automated renewal cron & app restart logic
=> feat: helm hook for first cert provision

helm/cas-ciip-portal/values-wksv3k-dev.yaml
cas-postgres's create-user-db doesn't reset owner
if the user already exists
=> fix: ciip user needs to be dropped on dev

app/package.json
This makes the app crash when the graphile worker fails to connect to the db,
instead of silently continuing to work
=> feat: yarn start uses --unhandled-rejections=strict option

app/components/SearchBox.tsx, app/components/SearchTable.tsx, app/components/SearchTableLayout.tsx
Setting the searchValue depended on the searchField being set in state, but the searchField handleEvent was happening first, causing a re-render and refetch before searchValue was set. Setting both values in state at the same time fixes the issue
https://youtrack.button.is/issue/GGIRCS-1598
=> fix: searchTable reset button behaving badly

app/containers/Forms/SummaryEmissionGasFields.tsx
values of 0 were being treated as falsey in the logic determining whether to display the value or NO DATA ENTERED. I fixed the logic to display the 0 instead of NO DATA ENTERED.
https://youtrack.button.is/issue/GGIRCS-1570
=> fix: diff table - NO DATA ENTERED

app/containers/Applications/ApplicationWizardConfirmation.tsx, app/server/emailTemplates/certificationRequest.js
Certification link copied to clipboard was missing the protocol at the beginning, causing it not to be a workable link if dropped into an email.
It was being hard coded in the certification request email, but this reverses that and fixes the root cause.
[GGIRCS-1690](https://youtrack.button.is/issue/GGIRCS-1690)
=> fix: Certifier clipboard URL should have protocol

app/server/index.js
- Configures a middleware setting the `X-Robots-Tag` header for all non-production domains, per [GGIRCS-1631](https://youtrack.button.is/issue/GGIRCS-1631)
* covers all assets, including static assets like images
* [read about the directives here](https://developers.google.com/search/reference/robots_meta_tag#directives)
=> Set robots header to noindex for non-production environments

app/components/Layout/Analytics.jsx
Slight modification requested by GDX to graduate us to the production-ready tracker. [GGIRCS-1671](https://youtrack.button.is/issue/GGIRCS-1671)
This is still in our test env only, and they'll do another round of tests and give us the okay to deploy it in our prod environment.
=> Update snowplow collector to production origin

app/components/Layout/Header.tsx, app/components/RegistrationLoginButtons.tsx, app/server/index.js, app/tests/unit/components/Layout/__snapshots__/Header.test.tsx.snap
Direct link to SSO registration page per [GGIRCS-1703](https://youtrack.button.is/issue/GGIRCS-1703).
Adds 2 public runtime env variables to the Next config: 
- `HOST`
* to compute the post-registration `redirect_uri`
- `NAMESPACE`
* to compute the keycloak namespace to link to (ie: `sso[-dev|-test].pathfinder` vs. `sso.pathfinder`)
We've decided to ship this for now without support for post-registration redirects, due to some difficulties that would add precious time to debug before impending use by the public. We'll prioritize and revisit support at a later date. Those difficulties are:
- Return trip to `/login` after registering returns a 403 (however the user is still created, and subsequently clicking "Login" automatically logs them in).
- the login service improperly decodes the …
=> Register button leads directly to SSO registration page

app/package.json, app/yarn.lock
see https://www.npmjs.com/advisories/1523/versions
=> chore: pin lodash version to 4.17.18 to resolve npm security advisory

app/package.json, app/yarn.lock
4.17.18 is now affected by
https://www.npmjs.com/advisories/1523/versions
=> chore: update lodash to pass audit after revision of npm advisory

app/cypress/integration/application-form-validation.spec.js
This will stop false negatives in happo until mutations debounce is implemented
=> test: take administration form screenshot before typing data

app/layouts/default-layout.tsx, app/pages/user/profile.tsx, app/tests/unit/pages/user/__snapshots__/profile.test.tsx.snap
They will be redirected to their landing page
We don't have a test IDIR so we can't have an e2e test for this
=> fix: pending analysts should not be allowed on user/profile page

app/components/RegistrationLoginButtons.tsx
Fixes missing "type" attribute on login button accidentally introduced in #895 
[GGIRCS-1791](https://youtrack.button.is/issue/GGIRCS-1791)
=> fix: Ensure landing page login button submits

app/containers/Applications/ApplicationWizardConfirmation.tsx, app/cypress/integration/form-errors-prevent-submit.spec.js, app/cypress/integration/reporter-access-all-pages.spec.js, app/tests/unit/containers/Applications/__snapshots__/ApplicationWizardConfirmation.test.tsx.snap
Requires an email to be input before 'Submit for Certification' can be clicked.
- button is disabled by default
- typing an email enables the button
[GGIRCS-1831](https://youtrack.button.is/issue/GGIRCS-1831)
=> fix: Require certifier email before submitting for certification

app/containers/Applications/ApplicationRevisionStatusContainer.tsx, app/cypress/integration/email.spec.js, app/tests/unit/containers/Applications/ApplicationStatusContainer.test.tsx, app/tests/unit/containers/Applications/__snapshots__/ApplicationStatusContainer.test.tsx.snap
- adds a confirmation modal before applying change to application status
- adds some explanatory text under the Application Status dropdown
=> feat: status change confirmation

app/containers/Applications/ApplicationWizard.tsx, app/cypress/integration/reporter-certifier-access.spec.js, app/pages/certifier/certify.tsx, app/pages/reporter/application.tsx, app/server/schema.graphql, app/server/schema.json, app/tests/unit/pages/__snapshots__/certify.test.tsx.snap, app/tests/unit/pages/certify.test.tsx, schema/deploy/computed_columns/application_current_user_can_edit.sql, schema/revert/computed_columns/application_current_user_can_edit.sql, schema/sqitch.plan, schema/verify/computed_columns/application_current_user_can_edit.sql
- redirects certifier to /certify if they attempt to access the edit view via a url
- replaces signature component with 'application certified' if it has been certified
=> Fix: certifier redirected from edit view

schema/deploy/policies/review_comment_policies.sql, schema/deploy/policies/review_comment_policies@v1.1.0.sql, schema/revert/policies/review_comment_policies@v1.1.0.sql, schema/sqitch.plan, schema/test/unit/tables/review_comment_test.sql, schema/verify/policies/review_comment_policies@v1.1.0.sql
- updates policy file for review_comments table
=> fix: update rls to only hide 'internal' comments from industry user role

app/components/Application/ApplicationOverrideJustification.tsx, app/containers/Applications/ApplicationWizardConfirmation.tsx, app/tests/unit/components/ApplicationOverrideJustification.test.tsx, app/tests/unit/components/__snapshots__/ApplicationOverrideJustification.test.tsx.snap, app/tests/unit/containers/Applications/__snapshots__/ApplicationWizardConfirmation.test.tsx.snap
- ApplicationOverrideJustification component returns null if there are no errors present in the application
=> Fix: hide override if there are no errors

README.md, docs/all-views-inventory.md, docs/index.md
Documents all views on the CIIP website, organized by the user role(s) able to access the view.
- Concisely describes the purpose and functionality of each page, and the URL it can be viewed at
- Documents some quirks, such as pages that have query parameters required in the URL to prevent error
* specific query params for each such page are listed
- UI components that are shared across numerous views are listed to give an indication of the surface area touched by edits to a given component.
For easier reading: [view rendered markdown](https://github.com/bcgov/cas-ciip-portal/blob/docs/page-inventory/docs/all-views-inventory.md)
Links to documentation for entry from the repository index have also been created.
[GGIRCS-1807](https://youtrack.button.is/issue/GGIRCS-1807)
=> Document inventory of all views, organized by user role

app/containers/Forms/CertificationSignature.tsx, app/cypress/integration/reporter-certifier-access.spec.js, app/tests/unit/containers/Forms/__snapshots__/CertificationSignature.test.tsx.snap
Adds instruction text above digital signature pad for certifiers to understand how to sign.
[GGIRCS-1830](https://youtrack.button.is/issue/GGIRCS-1830)
=> Add instruction text above digital signature pad

README.md, app/components/LegalDisclaimerText.tsx, app/containers/Organisations/Organisations.tsx, app/pages/reporter/new-application-disclaimer.tsx, app/server/emailTemplates/certificationRequest.js, app/tests/unit/components/__snapshots__/LegalDisclaimerText.test.tsx.snap, app/tests/unit/containers/Organisation/__snapshots__/Organisations.test.tsx.snap, app/tests/unit/pages/reporter/__snapshots__/new-application-disclaimer.test.tsx.snap, docs/reporting-guide.md
Updates the CIIP program website URL to its (hopefully) [permanent content URL](https://www2.gov.bc.ca/gov/content?id=6F748A4DD83447C59B8B9361882FF9A3).
[GGIRCS-1874](https://youtrack.button.is/issue/GGIRCS-1874)
=> Update CIIP program website URL

app/containers/KeyDates.tsx, app/containers/RegistrationLoginButtons.tsx, app/tests/unit/containers/KeyDates.test.tsx, app/tests/unit/containers/RegistrationLoginButtons.test.tsx, app/tests/unit/containers/__snapshots__/RegistrationLoginButtons.test.tsx.snap
- Hides the first sentence of text (with deadline) above the "Register and Apply" button
- Hides the Key Dates dates, except for the application open time, which is in the past.
=> feat: Don't show application close time on front page

app/containers/Forms/CertificationSignature.tsx
- Fixes error in FireFox when uploading a signature file by defining width/height of uploaded image & ensuring it is smaller than the canvas area
=> fix: signature file upload error

app/containers/Forms/EmissionField.tsx, app/tests/integration/Forms/__snapshots__/Form.test.tsx.snap
Fixes "Hide gases with no emissions" button from overlapping the form 'Saving' indicator.
[GGIRCS-1925](https://youtrack.button.is/issue/GGIRCS-1925)
=> fix: Hide gases button shouldn't overlap 'saving' indicator

app/containers/Applications/ApplicationRevisionStatusContainer.tsx, app/tests/unit/containers/Applications/__snapshots__/ApplicationStatusContainer.test.tsx.snap
Transforms status indicator / dropdown selector on analyst application review into a 'pill' badge, as opposed to a rectangular dropdown button.
[GGIRCS-1624](https://youtrack.button.is/issue/GGIRCS-1624)
=> fix: Status indicators should appear as a pill badge

.circleci/config.yml
=> chore: remove acceptance step from ci config

helm/cas-ciip-portal/templates/cron-app-users.yaml
The last line of cron-app-users was always failing (function call that creates the policies for the read-only user). The user parameter needed to be wrapped in quotes, otherwise it is treated as a column by psql.
This should fix the problem in metabase where nobody can see any ciip data.
=> fix: read-only-user policies

helm/cas-ciip-portal/templates/cron-app-users.yaml
escape quotes in bash command (variable was still not wrapped properly)
=> fix: read-only user part II

helm/cas-ciip-portal/templates/cron-app-users.yaml
- remove escape characters from bash function call
=> fix: read-only policies

app/components/PageRedirectHandler.tsx, app/pages/login-redirect.tsx, app/server/index.js, app/tests/unit/pages/__snapshots__/login-redirect.test.tsx.snap, app/tests/unit/pages/login-redirect.test.tsx, docs/stack.md
In order to test this PR, you should reduce the `SSO Session Idle` setting in keycloak to 2/3 minutes, and the `Access token lifespan` to something smaller.
You should not encounter any issue as long as you keep interacting with the application (contrary to the current behavior where you get logged out either way).
If you wait for the time you set in the SSO Session Idle, you should get redirected to the `login-redirect` page, asking you to log in again
=> fix: keycloak access token is refreshed when needed

.circleci/config.yml
This should make the CircleCI ui less confusing, and marking the test workflow as a `success` instead on `on hold`
=> chore: move release CI jobs in a separate workflow

README.md, docs/CODE_OF_CONDUCT.md, docs/CONTRIBUTING.md, docs/README.md
No rush, but thought I'd put this up since it's a boilerplate job [from DevHub](https://developer.gov.bc.ca/Code-Management/Sample-Code-of-Conduct).
@Maralsotoudehnia let me know what would be an appropriate [email contact to direct abuse reports to](https://github.com/bcgov/cas-ciip-portal/compare/docs/code-of-conduct?expand=1#diff-bf5ab2816dd1ffeb0c1a2ce8d3077160R57-R58) - I filled in yours to start.
Note the [Scope section](https://github.com/bcgov/cas-ciip-portal/compare/docs/code-of-conduct?expand=1#diff-bf5ab2816dd1ffeb0c1a2ce8d3077160R46-R53) applies the code of conduct to several relevant mediums.
=> Add code of conduct from DevHub

docs/dev-environment-setup.md, docs/developer-guide.md
I was surprised to learn we had a new `AS_PENDING` dev flag, so noticed it needed to be added to the docs. `AS_CERTIFIER` was also missing, so added that as well.
=> Add AS_PENDING and AS_CERTIFIER flags to docs

app/components/AddOrganisationModal.tsx, app/containers/Facilities/AddFacility.tsx, app/containers/Organisations/AddOrganisation.tsx, app/tests/unit/components/__snapshots__/AddOrganisationModal.test.tsx.snap
Updates the `/analyst/add-facility` and `/analyst/add-organisation` tables in the analyst view to be in line with the BCGov style guide as specified in [GGIRCS-1619](https://youtrack.button.is/issue/GGIRCS-1619#focus=streamItem-4-3165.0-0) (table header color and vertical centering of row content). See YT card for screenshots.
=> Apply BCGov style guide to Add Org/Facility tables

app/containers/Applications/ApplicationDetailsPdf.tsx, app/containers/Pdf/PdfFuelFieldsTemplate.tsx, app/tests/unit/containers/Applications/ApplicationDetailsPdf.test.tsx, app/tests/unit/containers/Applications/__snapshots__/ApplicationDetailsPdf.test.tsx.snap
Fixes issue where fuelRowId & emissionCategoryRowId were not being parsed from integer IDs to their corresponding named values in the PDF.
=> Fix: PDF fuel/emission category ID parsing

app/containers/Applications/ApplicationDetailsContainer.tsx, app/containers/Applications/ApplicationWizardConfirmation.tsx, app/containers/Forms/CertificationSignature.tsx, app/cypress/integration/override-justification.spec.js, app/tests/unit/containers/Applications/__snapshots__/ApplicationDetailsContainer.test.tsx.snap, app/tests/unit/containers/Applications/__snapshots__/ApplicationWizardConfirmation.test.tsx.snap, app/tests/unit/containers/Forms/__snapshots__/CertificationSignature.test.tsx.snap
@matthieu-foucault I noticed a couple more tweaks I wanted to add to #1214 after it was merged:
- Shows the program title and logo from the site header in print (just not the navigation)
- Opens the PDF download in a new tab
- Hides the certification signature interface in print
- not interactive on paper
- if they have signed before printing, it won't be visible in the PDF anyway, which is confusing
- Replaces the non-interactive "expand" link to the full text disclaimer with the full URL of the link destination.
(web view):
(print view):
[GGIRCS-2037](https://youtrack.button.is/issue/GGIRCS-2037)
=> PDF Download style tweaks

.circleci/config.yml, app/.env.example, app/cypress/integration/accessibility/certifier-all-pages-accessibility.spec.js, app/cypress/integration/reporter-certifier-access.spec.js, app/cypress/support/commands.js, app/server/helpers/databaseMockPgOptions.js
This PR creates `cy.useMockedTime(date: Date)` and `cy.clearMockedTime()` helper commands to set and clear the mocked database time.
For this to work:
- `ENABLE_DB_MOCKS` or `ENABLE_DB_MOCKS_COOKIES_ONLY` environment variables need to be set
- the `mocks` schema needs to be deployed
=> Cypress helper method to use the mocks schema

app/containers/Admin/ReportingYear/NewReportingYearFormDialog.tsx, app/containers/Admin/ReportingYear/ReportingYearFormDialog.tsx, app/containers/Admin/ReportingYear/ReportingYearTable.tsx, app/containers/Admin/ReportingYear/reportingYearValidation.ts, app/tests/unit/containers/Admin/ReportingYear/reportingYearValidation.test.ts, app/tests/unit/containers/ReportingYear/__snapshots__/ReportingYearFormDialog.test.tsx.snap
- If there's currently an open application window, then no previous application window dates can be changed
- prevents overlapping application windows, which the system cannot handle
- If there's **no** open application window, then the most recently closed application close date can be changed
- Adds validation to ensure when editing date ranges a) for the application window, and b) for the reporting years start/end that the proposed dates do not overlap with that of another reporting period.
[GGIRCS-2022](https://youtrack.button.is/issue/GGIRCS-2022)
=> Allow editing of the last application close date, even if past

app/containers/Applications/ReviseApplicationButtonContainer.tsx, app/tests/unit/containers/Applications/ReviseApplicationButtonContainer.test.tsx, app/tests/unit/containers/Applications/__snapshots__/ReviseApplicationButtonContainer.test.tsx.snap
In viewing a submitted application (for example from an old email link requesting changes to the application) at `/reporter/view-application`, if a newer draft has already been created, the "Revise" button will instead show:
a) "Resume latest draft" if the latest draft's version number is greater than the latest submitted version
b) "View most recent submission" if they're viewing a really old version, where a new version has already been revised and submitted
* even if this newer submission has had changes requested, they can first navigate to the newer submission to view analyst comments before clicking either "Revise" or "Resume latest draft" on that version.
There is no change in appearance or behavior for the case where the submitted revision is still the most recent revision. …
=> "Revise Application" button should be "Resume Latest Draft" if one exists

docs/developer-guide.md
fixes a small typo in our developer guide
=> fix: typo in developer guide documentation

.tool-versions, app/package.json
Fixes high-severity CVE-2020-8265
=> fix: upgrade nodejs to 12.20.1

.circleci/config.yml, app/server/index.js, helm/cas-ciip-portal/templates/deploy.yaml
- add a /health endpoint that queries the database (and checks for recovery mode)
- use /health in deploy.yaml template as the readiness probe target path
=> feat: health endpoint

app/cypress/integration/application-form-validation.spec.js, app/cypress/integration/index.spec.js, app/cypress/integration/product-benchmark.spec.js, app/cypress/integration/reporter-certifier-access.spec.js, app/layouts/default-layout.tsx, app/tests/unit/layout/__snapshots__/default-layout.test.tsx.snap
- Updates the sitewide default layout such that the `html` and `body` tags encompass their entire content
- Updates Happo screenshots in Cypress tests to snapshot content of the `body` tag instead of a subset
[GGIRCS-1984](https://youtrack.button.is/issue/GGIRCS-1984)
- Cleans up the reporter-certifier-access-spec, which was getting disorganized and a bit nonsensical
- broke cases out into individual tests
=> Happo snapshots should frame entire page

app/components/Benchmark/PastBenchmarks.tsx, app/components/HeaderWidget.tsx, app/containers/Products/ProductCreatorContainer.tsx, app/containers/Products/ProductListContainer.tsx, app/containers/Products/ProductRowItemContainer.tsx, app/cypress/integration/accessibility/admin-all-pages-accessibility.spec.js, app/cypress/integration/product-benchmark.spec.js, app/tests/unit/containers/Products/__snapshots__/productListContainer.test.tsx.snap, app/tests/unit/containers/Products/__snapshots__/productRowItemContainer.test.tsx.snap, app/tests/unit/containers/Products/productRowItemContainer.test.tsx
- Re-orders products table columns
- Renames column heading for product settings
- Implements a product settings button with dropdown menu to open existing settings dialogs
- Updates related admin/analyst help documentation
- Enables accessibility tests for manage products page
- **Note**: there will be more work to be done for the tests with open dialogs to pass (due to spurious contrast violations, and to an issue with the page body underneath the overlay still being focusable when dialog is open). These are skipped for now.
- Upgrades unit tests for `productRowItemContainer` to be more functional / complementary to the snapshot
[GGIRCS-2190](https://youtrack.button.is/issue/GGIRCS-2190)
=> Product settings

app/components/helpers/HelpButton.tsx, app/layouts/default-layout.tsx, app/tests/unit/components/helpers/HelpButton.test.tsx, app/tests/unit/components/helpers/__snapshots__/HelpButton.test.tsx.snap
[GGIRCS-2188](https://youtrack.button.is/issue/GGIRCS-2188)
- Help button is present on all logged-in views for analysts and admins
- "Report a problem to the development team" temporarily opens a mailto link (new email with subject line "Internal Support Request") directed to `SUPPORT_EMAIL`. This URL should be updated when/if we have a new issue reporting system.
- Documentation links to Github admin/analyst guide on master. It's not amazingly thorough, but we can update either the link destination or improve the docs as appropriate.
=> Fixed help button for admins/analysts

app/components/FilterableComponents/FilterableTableHeaders.tsx
The offset value was not being reset, leaving the user on a non-existent page when the results got pared down via a filter.
=> fix: reset offset when applying new search filters

.bin/sqitch-check-immutable-files.sh, schema/revert/database_functions/create_portal_app_user.sql
dropping the user during revert caused an issue during `make test` when both the local _dev and _test databases existed. The deploy does a `create if not exists...` anyway.
=> fix: don't drop ciip_portal user during revert

app/components/Application/ApplicationDecision.tsx, app/components/Forms/ApplicationFormNavbar.tsx, app/containers/Applications/ApplicationWizard.tsx, app/containers/Applications/ApplicationWizardStep.tsx, app/containers/Applications/ReviseApplicationButtonContainer.tsx, app/pages/reporter/view-application.tsx, app/tests/unit/components/Application/ApplicationDecision.test.tsx, app/tests/unit/components/Application/__snapshots__/ApplicationDecision.test.tsx.snap, app/tests/unit/containers/Applications/ReviseApplicationButtonContainer.test.tsx, app/tests/unit/containers/Applications/__snapshots__/ReviseApplicationButtonContainer.test.tsx.snap, app/tests/unit/pages/__snapshots__/view-application.test.tsx.snap, app/tests/unit/pages/view-application.test.tsx
On `/reporter/view-application`:
- See [screenshots](https://youtrack.button.is/issue/GGIRCS-2297#focus=streamItem-4-4629.0-0) of all the possible decision/revision/submission states that an application can be in.
- Moves the 'View latest submission' and 'Resume latest draft' buttons into the main page for DOM reasons
On `/reporter/application`:
- Replaces ApplicationCommentsContainer with new revamped ApplicationDecision component (re-used from the above page) - see [screenshot](https://youtrack.button.is/issue/GGIRCS-2297#focus=streamItem-4-4692.0-0)
[GGIRCS-2297](https://youtrack.button.is/issue/GGIRCS-2297)
=> Reporter-facing side of application review

schema/deploy/tables/review_step.sql
Adds an insert in the migration to create the default [legacy, administrative, technical] steps into the table
=> refactor: insert default review_steps in migration

.circleci/config.yml, .tool-versions, schema/test/unit/database_functions/upsert_policy_test.sql, schema/test/unit/mutations/create_application_revision_mutation_chain_test.sql
Updating postgres version in the asdf tools, for development and test environments only.
cas-postgres uses 12.2 on the patroni HA cluster
=> Chore: updating tools-version to postgres 12.6

app/components/Admin/CreateNaicsCodeModal.tsx, app/components/Admin/DeleteConfirmationModal.tsx, app/containers/Admin/NaicsCode/NaicsCodeTable.tsx, app/tests/unit/components/Admin/DeleteConfirmationModal.test.tsx, app/tests/unit/components/Admin/__snapshots__/DeleteConfirmationModal.test.tsx.snap, app/tests/unit/containers/Admin/NaicsCodes/__snapshots__/NaicsCodeTable.test.tsx.snap
=> refactor: naics UI improvements

app/server/index.js
The SSL issuer may ask to verify the domain when renewing a certificate
=> fix: acme-challenge should be served even when using https

test_helper_schema/deploy/mock_open_window.sql, test_helper_schema/verify/mock_open_window.sql
This adds a input parameter to `test_helper_schema.mock_open_window( )`
- will modify the reporting year passed in to open `now() - 1 day` and close `now() + 1 day`
- defaults to reporting year 2019
=> test: mock_open_window accepts a year to mock as open

app/components/Layout/Footer.tsx, app/components/helpers/CookieDayPickerInput.tsx, app/containers/Admin/ApplicationReview/ReviewSidebar.tsx, app/cypress/integration_mocks/database-date-mock.spec.js, app/layouts/default-layout.tsx, app/pages/analyst/application-review.tsx, app/tests/unit/containers/Admin/ApplicationReview/__snapshots__/ReviewSidebar.test.tsx.snap
Fixes layout issue in application review sidebar when the SiteNoticeBanner is toggled on, as noted in [GGIRCS-2193](https://youtrack.button.is/issue/GGIRCS-2193).
Does not currently address the annoying superposition of the DB datepicker, which is only present in dev/test.
Start the server with both the above components turned on:
```
SITEWIDE_NOTICE="<div class='alert alert-info'>This is the LOCALHOST environment.</div>" ENABLE_DB_MOCKS=true yarn dev AS_ADMIN
```
=> Fix: Account for potential header offset in ReviewSidebar caused by SiteNoticeBanner

docs/release.md
- Adds (obvious? 😅) step to merge release PR before continuing to CI release workflow
- Clarifies the local merge steps that must be done for `develop` --> `master`
- Updates the URL for Shipit
=> Refine docs on release process

app/containers/Forms/EmissionCategoryRowIdField.tsx, app/containers/Forms/FuelField.tsx, app/tests/unit/containers/Forms/EmissionCategoryRowIdField.test.tsx, app/tests/unit/containers/Forms/FuelField.test.tsx, app/tests/unit/containers/Forms/__snapshots__/EmissionCategoryRowIdField.test.tsx.snap, app/tests/unit/containers/Forms/__snapshots__/FuelField.test.tsx.snap, schema/data/deploy-data.sh, schema/data/dev/application.sql, schema/data/dev/application_submission.sql, schema/data/dev/ciip_user_organisation.sql, schema/data/dev/form_result.sql, schema/data/dev/product.sql, schema/data/prod/emission.sql, schema/test/data/dev_data_test.sql, schema/test/unit/tables/ciip_user_organisation_test.sql
Deprecating the 'other, non carbon-taxed' emission category
This feature will make sure that any emission category with the 'deleted_at' field set will render as read-only in existing applications, and won't be shown as an option for new applications.
=> Feat: allow deprecation of emission categories

app/components/ProgressStepIndicator.tsx, app/components/helpers/StatusBadgeColor.tsx, app/containers/Organisations/Organisations.tsx, app/containers/Organisations/UserOrganisation.tsx, app/cypress/integration/reporter-access-all-pages.spec.js, app/layouts/default-layout.tsx, app/pages/reporter/index.tsx, app/tests/unit/components/ProgressStepIndicator.test.tsx, app/tests/unit/components/__snapshots__/ProgressStepIndicator.test.tsx.snap, app/tests/unit/containers/Organisation/__snapshots__/Organisations.test.tsx.snap, app/tests/unit/layout/__snapshots__/default-layout.test.tsx.snap, app/tests/unit/pages/reporter/__snapshots__/index.test.tsx.snap
Introducing a reusable UI component to show process steps as a static progress bar.
it can be customized with:
- step #
- badge colour
- description
This refactors the reporter's organisation view with a clearer indication of the status of his access requests.
=> Feat: operator access progress indicator

.circleci/config.yml, app/.env.example, app/containers/Applications/ApplyButtonContainer.tsx, app/containers/Facilities/FacilitiesListContainer.tsx, app/containers/Organisations/Organisations.tsx, app/next.config.js, app/pages/resources/contact.tsx, app/server/helpers/getEmailShortForm.js, app/server/tasks/sendMail.js, app/tests/unit/containers/Applications/__snapshots__/ApplyButtonContainer.test.tsx.snap, app/tests/unit/containers/Facility/__snapshots__/FacilitiesListContainer.test.tsx.snap, app/tests/unit/containers/Organisation/__snapshots__/Organisations.test.tsx.snap, app/tests/unit/pages/resources/__snapshots__/contact.test.tsx.snap, helm/cas-ciip-portal/values-dev.yaml, helm/cas-ciip-portal/values-test.yaml, helm/cas-ciip-portal/values.yaml
https://youtrack.button.is/issue/GGIRCS-1557
https://youtrack.button.is/issue/GGIRCS-2015
- Update email contact depending on help location
- cleans up all env vars related to emails.
MOBILE:
DESKTOP:
=> fix: update contact us page email locations

app/components/Application/ApplicationOverrideNotificationCard.tsx, app/components/GenericConfirmationModal.tsx, app/containers/Admin/ApplicationReview/ApplicationReviewStepSelector.tsx, app/containers/Admin/ApplicationReview/ReviewSidebar.tsx, app/containers/Applications/ApplicationDetailsContainer.tsx, app/containers/Applications/ApplicationRevisionStatusContainer.tsx, app/containers/Incentives/IncentiveCalculatorContainer.tsx, app/pages/analyst/application-review.tsx, app/tests/unit/components/GenericConfirmationModal.test.tsx, app/tests/unit/components/__snapshots__/ApplicationOverrideNotificationCard.test.tsx.snap, app/tests/unit/components/__snapshots__/GenericConfirmationModal.test.tsx.snap, app/tests/unit/containers/Admin/ApplicationReview/ApplicationReviewStepSelector.test.tsx, app/tests/unit/containers/Admin/ApplicationReview/ReviewSidebar.test.tsx, app/tests/unit/containers/Admin/ApplicationReview/__snapshots__/ApplicationReviewStepSelector.test.tsx.snap, app/tests/unit/containers/Admin/ApplicationReview/__snapshots__/ReviewSidebar.test.tsx.snap, app/tests/unit/containers/Applications/__snapshots__/ApplicationDetailsContainer.test.tsx.snap, app/tests/unit/containers/Applications/__snapshots__/ApplicationStatusContainer.test.tsx.snap, app/tests/unit/containers/Incentives/__snapshots__/IncentiveCalculatorContainer.test.tsx.snap, app/tests/unit/pages/analyst/__snapshots__/application-review.test.tsx.snap, app/tests/unit/pages/analyst/application-review.test.tsx
- Review step selector shows selected review step in sidebar
- Shows completion state of each step
* marking a step complete shows a confirmation modal when there remain unresolved comments, requested by SME
- "Make a decision or request changes" button remains disabled until all steps are marked completed
* once a decision is made, text/color/icon indicates the decision
- "Change decision" button preserves current functionality for admins (but not analysts, per SME) to change the decision
* actual making/changing of decision will be implemented in [GGIRCS-2294](https://youtrack.button.is/issue/GGIRCS-2294) when the status dropdown will finally be removed.
* disabled when a newer draft exists
* instead, disabled button indicates the existence of newer draft
- Once a decision is made, …
=> Review step selector on application review page

schema/deploy/tables/review_step_001.sql, schema/revert/tables/review_step_001.sql, schema/sqitch.plan, schema/verify/tables/review_step_001.sql
...Again. Realized how it shows up as 'Other Review' in the review sidebar was awkward and confusing once I presented it in sprint review. But @matthieu-foucault had a brainwave to name it "application" so it shows up as "Application Review".
This is only relevant to pre-existing reviews created prior to this year.
=> Update legacy review_step name from 'other' to 'application'

app/containers/Products/ProductListContainer.tsx, app/containers/Products/ProductRowItemContainer.tsx, app/pages/analyst/organisation-requests.tsx, app/tests/unit/containers/Products/__snapshots__/productListContainer.test.tsx.snap, app/tests/unit/containers/Products/__snapshots__/productRowItemContainer.test.tsx.snap
Product sorting bug:
The column to sort on was passed incorrectly to the filter component.
date_modified -> updated_at
Organisation request table bug:
Page was missing getInitialProps() so it wasn't setting the relay variables on first load
=> Fix: product sort by date crash

app/components/Admin/AddReviewCommentModal.tsx, app/containers/Admin/ApplicationReview/ReviewSidebar.tsx, app/mutations/application_review_step/createReviewCommentMutation.ts, app/tests/unit/components/Admin/AddReviewCommentModal.test.tsx, app/tests/unit/components/Admin/__snapshots__/AddReviewCommentModal.test.tsx.snap, app/tests/unit/containers/Admin/ApplicationReview/ReviewSidebar.test.tsx, app/tests/unit/containers/Admin/ApplicationReview/__snapshots__/ReviewSidebar.test.tsx.snap, app/tests/unit/mutations/application_review_step/createReviewCommentMutation.test.ts
- 'New Comment' button in review sidebar opens simplified modal to write a comment and add it to the selected review step
- Checkbox defines the comment type, aka. intended audience for the comment (`general` for applicants to see, or for `internal` use only)
- Visibility indicator confirms who can see the comment before completing the action
- Comment is saved and associated to the review step to which it was added
[GGIRCS-2194](https://youtrack.button.is/issue/GGIRCS-2194)
=> Re-enable review comment creation with simplified modal

shipit.dontdeployme.yml, shipit.prod.yml, shipit.yml
I think the iframe will have an issue unless we make the dashboard public in sysdig?
=> chore: add sysdig links/monitoring to shipit

helm/cas-ciip-portal/templates/cronJobs/cron-deploy-data.yaml
same as in cas-ggircs repo, parenthesis need to be removed
"$(NAMESPACE)" --> "$NAMESPACE"
=> chore: remove bad parenthesis in helm template

schema/data/dev/create_dev_applications.sql
The dev data PR was being done in parallel with the 'remove _send_draft_email trigger' PR. They got merged back to back and a reference to the removed trigger was left in the dev data.
tldr: This fixes the broken develop branch
=> refactor: remove deprecated trigger from new dev data

app/containers/Forms/ProductField.tsx, app/cypress/integration/accessibility/reporter-all-pages-accessibility.spec.js, app/cypress/integration/analyst-diffing.spec.js, app/cypress/integration/application-form-validation.spec.js, app/cypress/integration/override-justification.spec.js, app/tests/unit/containers/Forms/__snapshots__/ProductField.test.tsx.snap, schema/data/prod/form_json.sql
https://youtrack.button.is/issue/GGIRCS-1361
Tab “Administration Data” and its heading:
- Rename tab and heading to “Administrative Data”
- Rename heading “Operational Representative” to “Operation Representative”
- Rename heading “Operational Representative Mailing Address” to “Operation Representative Mailing Address”
Tab “Emission” and its heading:
- Rename tab and heading to “SWRS Onsite Emissions”.
Tab “Fuel” and its heading:
- Rename tab and heading to “Fuels”.
Tab “Production” and its heading:
- Rename tab and heading to “Production and Emissions Allocation”.
=> feat: change names of ciip application tab titles

app/components/Application/ScrollableApplicationDisclaimer.tsx, app/components/LegalDisclaimerText.tsx, app/containers/Applications/ApplicationWizardConfirmation.tsx, app/containers/Organisations/Organisations.tsx, app/pages/resources/copyright.tsx, app/pages/resources/privacy.tsx, app/tests/unit/components/Application/ScrollableApplicationDisclaimer.test.tsx, app/tests/unit/components/Application/__snapshots__/ScrollableApplicationDisclaimer.test.tsx.snap, app/tests/unit/components/__snapshots__/LegalDisclaimerText.test.tsx.snap, app/tests/unit/containers/Applications/__snapshots__/ApplicationWizardConfirmation.test.tsx.snap, app/tests/unit/containers/Organisation/__snapshots__/Organisations.test.tsx.snap, app/tests/unit/pages/resources/__snapshots__/copyright.test.tsx.snap, app/tests/unit/pages/resources/__snapshots__/privacy.test.tsx.snap
- Updates the legal text component for the application disclaimer
- Adds a scrollable area to display the legal disclaimer just before submission, with new paragraph text above the legal disclaimer
* this also updates the text on the page shown at `/resources/application-disclaimer` (which is currently only linked from the "expand" link on the scrollable area)
* links to GGIRCA and the expanded disclaimer page open in a new tab
* `adminEmail` runtime variable is used for the email address at the end
**Incidental:**
- Updates all external links sitewide to use https:// instead of http:// where supported
* necessary to please SonarCloud for the bclaws website linked in the legal disclaimer, so I did them all at once
[GGIRCS-2244](https://youtrack.button.is/issue/GGIRCS-2244)
=> Updated application disclaimer text before submission

app/components/Forms/SearchDropdownWidget.tsx, app/containers/Applications/ApplicationWizardStep.tsx, app/containers/Forms/Form.tsx, app/containers/Forms/FormArrayFieldTemplate.tsx, app/containers/Forms/ProductField.tsx, app/containers/Forms/ProductRowIdField.tsx, app/containers/Forms/ProductsArrayField.tsx, app/pages/_app.tsx, app/tests/unit/containers/Forms/ProductField.test.tsx, app/tests/unit/containers/Forms/ProductsArrayField.test.tsx, app/tests/unit/containers/Forms/__snapshots__/Form.test.tsx.snap, app/tests/unit/containers/Forms/__snapshots__/ProductField.test.tsx.snap, app/tests/unit/containers/Forms/__snapshots__/ProductsArrayField.test.tsx.snap, schema/data/prod/form_json/production.json
- If a NAICS code has been set in the Administrative Data section, any mandatory products are initialized in the Production section.
- Adds custom ProductsArrayField to accomplish this by mutating the formResult on load
- "Remove product" button is overridden on a per-item basis for mandatory products
[GGIRCS-2288](https://youtrack.button.is/issue/GGIRCS-2288)
=> Initialize and enforce mandatory products on reporter side

app/pages/reporter/application/[applicationId]/version/[versionNumber]/disclaimer.tsx, app/tests/unit/pages/reporter/application/[applicationId]/version/[versionNumber]/__snapshots__/disclaimer.test.tsx.snap
Updates the consent text displayed at `/reporter/application/[applicationId]/version/[versionNumber]/disclaimer`.
**Note:** There is a second blurb, starting with "We found an emissions report..." when the application has data imported from SWRS that is only shown when `?hasSwrsReport=true` - this can be demo'd just by changing the `hasSwrsReport` query param.
[GGIRCS-2440](https://youtrack.button.is/issue/GGIRCS-2440)
=> Update interstitial consent text for new applications

schema/data/dev/form_result.sql, schema/data/prod/ciip_application_wizard.sql, schema/test/unit/computed_columns/application_ordered_form_results_test.sql
- Adds a pgTap test for `application_ordered_form_results()`
- Updates `data/prod/ciip_application_wizard` to use `on conflict` instead of `truncate..` & adds the inactive `admin` legacy form_json
- Small fixes to dev data to use the `is_active` column when creating dev form results
=> Fix: show legacy form json

app/containers/Organisations/Organisations.tsx
This has long been defunct since the implementation of row-level security, and only serves to confuse new team members.
=> Remove defunct 'activate org access' button on localhost

app/components/helpers/Toaster.tsx, app/containers/Applications/ApplicationWizardStep.tsx, app/containers/Products/ProductCreatorContainer.tsx, app/mutations/BaseMutation.ts, app/pages/admin/products-benchmarks.tsx, app/static/base.css
- Refactors the styling of the react-toastify toaster used in BaseMutation to appear similar to Bootstrap Alerts, which we use for static user messaging
- top center placement
- Converts the `/admin/products-benchmarks` page to use the BaseMutation success message instead of [yet another](https://react-bootstrap.netlify.app/components/toasts/) different Toast
[GGIRCS-1639](https://youtrack.button.is/issue/GGIRCS-1639)
=> Convert style of dynamic toast messages to be like Bootstrap Alerts

app/pages/reporter/application/[applicationId]/version/[versionNumber]/view.tsx, app/tests/unit/pages/reporter/application/[applicationId]/version/[versionNumber]/__snapshots__/view.test.tsx.snap, app/tests/unit/pages/reporter/application/[applicationId]/version/[versionNumber]/view.test.tsx
- [GGIRCS-2325](https://youtrack.button.is/issue/GGIRCS-2325) Uses state to hold `newerDraftExists` variable when presenting the option to revise to prevent flashing "Resume latest draft" after clicking Revise
- [GGIRCS-2457](https://youtrack.button.is/issue/GGIRCS-2457)
- Part A: Show the correct version number when viewing a submitted application
- Part B: When viewing submitted applications that have subsequent drafts, the version number should be shown
=> Bugfixes: Prevent "Resume" button flash on Revise + show version number when viewing submitted

app/mutations/user_organisation/createUserOrganisation.ts
Fixes [GGIRCS-2451](https://youtrack.button.is/issue/GGIRCS-2451):
The dropdown attempts to filter out orgs the user has already requested access to. However, `ciipUserOrganisationEdge.node.organisationId` is undefined for access requests done after page load, because it was not returned by the mutation.
=> Only show operations in dropdown that the user has not yet requested access to

app/components/FilterableTable/FilterableTableFilterRow.tsx, app/tests/unit/components/FilterableTable/__snapshots__/FilterableTable.test.tsx.snap, app/tests/unit/components/FilterableTable/__snapshots__/FilterableTableFilterRow.test.tsx.snap
Fixing an issue where setting `display: flex` on a single `<td>` element would cause small rendering issues in a bootstrap table.
=> fix: fixing double-margin around flex table cell

schema/data/prod/form_json/administration.json
Makes it so the 2019 admin form does not use the custom NAICS field. This allows invalid NAICS codes that were entered for 2019 applications before we restricted and validated the input to render
=> fix: display 2019 NAICS codes

app/mutations/product/createProductMutation.ts
updating the create product mutation so that the relay store receives empty lists for benchmarks and linked products
=> fix: new products can be edited

app/containers/Applications/ApplyButtonContainer.tsx, app/pages/resources/copyright.tsx, app/tests/unit/containers/Applications/__snapshots__/ApplyButtonContainer.test.tsx.snap, app/tests/unit/pages/resources/__snapshots__/copyright.test.tsx.snap
- Fixes two broken links in footer copyright page due to use of relative URLs in the boilerplate we used:  [GGIRCS-2458](https://youtrack.button.is/issue/GGIRCS-2458)
- Similar: external link to regulation from "missing SWRS report" warning opens in a new tab
=> Fix broken links on footer copyright page

app/components/Forms/AddCommentField.tsx, app/components/helpers/Toaster.tsx
One last toast that managed to escape restyling in #1697 as part of [GGIRCS-1639](https://youtrack.button.is/issue/GGIRCS-1639) - when saving a comment related to one of the application form fields.
=> One more place to Bootstrapify a dynamic toast

app/containers/Applications/ApplicationWizardStep.tsx
The latest update to Relay slightly changed how we should write the 'onComplete' form callback.
Bonus: we await on relay store update
=> fix: error message on 'Save & Continue' click

app/components/AddOrganisationModal.tsx, app/components/Dashboard/formConfiguration.tsx, app/components/Dashboard/reportingOperations.tsx, app/containers/Organisations/AddOrganisation.tsx, app/cypress/integration/analyst-access-all-pages.spec.js, app/pages/analyst/add-organisation.tsx, app/pages/analyst/organisation-requests.tsx, app/tests/unit/components/AddOrganisationModal.test.tsx, app/tests/unit/components/__snapshots__/AddOrganisationModal.test.tsx.snap
"Organisation" --> "Operation"
- on access requests page
- on search/add organisations page
- also updates the link wording in the admin dash from "Allowed Products" --> "Allowed & Mandatory Products"
\*Note: This does not update the word "organisation" where it occurs in URLs, eg: `/analyst/add-organisation` or `/analyst/organisation-requests`.
[GGIRCS-2367](https://youtrack.button.is/issue/GGIRCS-2367)
=> "Organisation" --> "Operation" in admin-facing UI

app/containers/Forms/ProductField.tsx, app/containers/Forms/ProductsArrayField.tsx
Fixes an issue where deleted product-naics-code associations still showed up if the product is mandatory
=> fix: mandatory products only populate on non-deleted associations

app/containers/Products/ProductRowItemContainer.tsx, app/mutations/product/updateProductMutation.ts, app/tests/unit/containers/Products/productRowItemContainer.test.tsx, schema/data/fixtures/analyst-all-access-setup.sql
- hides benchmark option in admin product page if the product is not a ciip benchmarked product.
- updates the updateProduct mutation to return the shape of the fragment (fixes a require-refresh bug)
=> Fix: conditional benchmark settings display

app/containers/Forms/ProductsArrayField.tsx
The updateProduct mutation in the mandatory products component (ProductsArrayField) was missing the energy product boolean fields, which caused the validation to skip the energy product validations since they were always being evaluated as false.
=> fix: add missing product fields to mandatory update mutation

.circleci/config.yml
don't run e2e snapshots if the unit/test-database steps fail
=> refactor: e2e step requires unit & test_database

.bin/sqitch-check-immutable-files.sh
The latter can cause a SIGPIPE
=> fix: use `sort -u` instead of `sort | uniq`

schema/data/prod/fuel.sql
So that historical carbon tax calculation is accurate
=> fix: archived Vented Natural Gas fuel should be mapped to Natural Gas

app/components/Admin/ApplicationReview/DecisionModal.tsx, app/cypress/integration/email.spec.js, app/tests/unit/components/Admin/ApplicationReview/DecisionModal.test.tsx, app/tests/unit/components/Admin/ApplicationReview/__snapshots__/DecisionModal.test.tsx.snap
fix for issue where clicking on the icon (not the button around) would trigger a `null` status for the application in the database
=> BugFix: clicking on the icon sends the right status

app/components/AddOrganisationModal.tsx, app/components/Admin/CreateNaicsCodeModal.tsx, app/components/Admin/DeleteConfirmationModal.tsx, app/components/helpers/LoadingOnClickButton.tsx, app/components/helpers/LoadingOnSubmitForm.tsx, app/containers/Admin/NaicsCode/NaicsCodeTable.tsx, app/containers/Admin/OrganisationRequestsTableRow.tsx, app/containers/Admin/ReportingYear/NewReportingYearFormDialog.tsx, app/containers/Admin/ReportingYear/ReportingYearFormDialog.tsx, app/containers/Applications/ReviseApplicationButtonContainer.tsx, app/containers/Facilities/AddFacilityModal.tsx, app/containers/Products/ProductCreatorContainer.tsx, app/containers/Products/ProductCreatorForm.tsx, app/lib/withPromiseLoading.tsx, app/tests/unit/components/Admin/DeleteConfirmationModal.test.tsx, app/tests/unit/components/Admin/NaicsCodeModal.test.tsx, app/tests/unit/components/Admin/__snapshots__/DeleteConfirmationModal.test.tsx.snap, app/tests/unit/components/Admin/__snapshots__/NaicsCodeModal.test.tsx.snap, app/tests/unit/containers/Admin/NaicsCodes/NaicsCodeTable.test.tsx, app/tests/unit/containers/Admin/NaicsCodes/__snapshots__/NaicsCodeTable.test.tsx.snap, app/tests/unit/containers/Applications/ReviseApplicationButtonContainer.test.tsx, app/tests/unit/containers/Applications/__snapshots__/ReviseApplicationButtonContainer.test.tsx.snap, app/tests/unit/containers/ReportingYear/__snapshots__/NewReportingYearFormDialog.test.tsx.snap, app/tests/unit/containers/ReportingYear/__snapshots__/ReportingYearFormDialog.test.tsx.snap
Refactoring of mutation buttons / forms to show a disabled state until the mutation is completed:
- Most Admin/analyst buttons
- 'Revise Application' button on the reporter side
=> Chore: refactor network triggers admin

.tool-versions, app/package.json
this updates nodejs to address
- CVE-2021-22883 
- CVE-2021-22884
=> chore: nodejs version update

app/server/schema.graphql, schema/data/prod/emission.sql, schema/deploy/computed_columns/application_revision_carbon_tax.sql, schema/deploy/computed_columns/application_revision_carbon_tax@v2.11.1.sql, schema/deploy/tables/emission_category_001.sql, schema/revert/computed_columns/application_revision_carbon_tax@v2.11.1.sql, schema/revert/tables/emission_category_001.sql, schema/sqitch.plan, schema/test/unit/computed_columns/application_revision_carbon_tax_test.sql, schema/test/unit/tables/emission_category_test.sql, schema/verify/computed_columns/application_revision_carbon_tax@v2.11.1.sql, schema/verify/tables/emission_category_001.sql
Some emission categories are not carbon taxed.
=> Fix: excluded emission categories

helm/cas-ciip-portal/Chart.yaml
The dag-trigger chart for the acme issue job is only pulled in when `route.insecure` is set
=> fix: acme issue dag is only triggered once

app/package.json, app/yarn.lock
=> chore: nodemailier patch update

app/package.json, app/yarn.lock, shipit.prod.yml
- Removed cucumber, it had a vulnerability and we're not using it CVE-2020-7677
- update terser-webpack-plugin CVE-2022-25858
- Allow deploy on audit failure.
=> Chore: audit deps

.github/actions/dev-env-setup/action.yml, cpanfile
No card. 
Removing [setup perl action](https://github.com/shogo82148/actions-setup-perl/releases) as the most recent release has been causing tests to fail. Using apt instead
=> chore: remove broken action install perl with apt

.gitignore, helm/cas-ciip-portal/.helmignore, helm/cas-ciip-portal/templates/jobs/terraform-apply.yaml, helm/cas-ciip-portal/templates/jobs/terraform-modules.yaml, helm/cas-ciip-portal/templates/jobs/terraform-service-account.yaml, helm/cas-ciip-portal/terraform/main.tf, helm/cas-ciip-portal/terraform/variables.tf, helm/cas-ciip-portal/values.yaml
[Issue](https://github.com/bcgov/cas-ciip-portal/issues/2276) - [Project link](https://github.com/orgs/bcgov/projects/123/views/2?filterQuery=tech+debt&pane=issue&itemId=51794275)
Adds Terraform scripts and Helm charts to run them. Resource states migrated from Terraform Cloud to a Google Cloud Storage bucket.
Changes 🚧
Added Terraform module, imported from cas-shelf
Added Helm templates to handle:
Terraform module loading to configMaps
OpenShift service account for use by Terraform
Terraform apply job
To test 🔬
The Helm charts are built into the automation around deploys via ShipIt. Once a deploy has been run, you can check the job Terraform-apply in OpenShift to see if the run was successful.
Notes📝
🔒 Terraform Cloud state has been locked to enable migration of state to state buckets …
=> 2276: Cas-Ciip Remove dependency on Terraform Cloud and cas-shelf

.gitignore, helm/cas-ciip-portal/templates/jobs/terraform-apply.yaml
When deploying via ShipIt, https://github.com/bcgov/cas-ciip-portal/pull/2277 failed with the following error. 
```bash
I0214 21:13:56.470711 3629 request.go:668] Waited for 1.10366045s due to client-side throttling, not priority and fairness, request: GET:https://10.98.0.1:443/apis/infrastructure.cluster.x-k8s.io/v1alpha5?timeout=32s
Error: UPGRADE FAILED: YAML parse error on cas-ciip-portal/templates/jobs/terraform-apply.yaml: error converting YAML to JSON: yaml: line 48: did not find expected key
```
Due to similar errors exposed in the past, attempting to resolve the error by removing comments and double quote.
=> Fix 2276 deploy
